import type { ProductCatalogItem } from './masterCatalogSeed.js';

// -------------------------------------------------------------
// TABLE 4 — ERH (ELECTRIC ROOM HEATERS / PANEL HEATERS) MASTER CATALOGUE
// -------------------------------------------------------------
export const RESEARCH_ERH_CATALOG: ProductCatalogItem[] = [
  // 1. Adax Neo NP 04 KDT
  {
    id: 'erh_adax_neo_np_04_kdt',
    family: 'ERH',
    brand: 'Adax',
    manufacturer: 'Adax (Norway)',
    product_family: 'Neo',
    model: 'Neo NP 04 KDT',
    sku: 'NCH04KWT',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 0.4,
    rated_output_kw: 0.4,
    output_w_delta_t50: 400,
    height_mm: 370,
    diameter_mm: 474, // Width
    depth_mm: 90,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Digital Timer, Electronic Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://adax.no/en/',
    manufacturer_product_url: 'https://adax.no/en/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Quality Heating',
    supplier_sku: 'NCH04KWT',
    price_ex_vat: 115.83,
    price_inc_vat: 139.00,
    price_source_url: 'https://qualityheating.co.uk/products/adax-neo-compact-wifi-modern-electric-convector-heater-white-2000-watts',
    price_date: '2026-09-14',
    notes: 'Adax Neo 400W panel heater. Size 370×474×90mm. 0% VAT eligible on ESM installation.',
    prices: [
      {
        supplier: 'Quality Heating',
        supplier_sku: 'NCH04KWT',
        source_url: 'https://qualityheating.co.uk/products/adax-neo-compact-wifi-modern-electric-convector-heater-white-2000-watts',
        price_basis: 'EX_VAT',
        price_ex_vat: 115.83,
        price_inc_vat: 139.00,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 2. Adax Neo NP 06 KDT
  {
    id: 'erh_adax_neo_np_06_kdt',
    family: 'ERH',
    brand: 'Adax',
    manufacturer: 'Adax (Norway)',
    product_family: 'Neo',
    model: 'Neo NP 06 KDT',
    sku: 'NEO-NP-06',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 0.6,
    rated_output_kw: 0.6,
    output_w_delta_t50: 600,
    height_mm: 370,
    diameter_mm: 589,
    depth_mm: 90,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Digital Timer, Electronic Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://adax.no/en/',
    manufacturer_product_url: 'https://adax.no/en/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'eBay',
    supplier_sku: 'NEO-NP-06',
    price_ex_vat: 115.83,
    price_inc_vat: 139.00,
    price_source_url: 'https://www.ebay.co.uk/shop/adax-neo',
    price_date: '2026-09-14',
    notes: 'Adax Neo 600W panel heater. Size 370×589×90mm. 0% VAT eligible on ESM installation.',
    prices: [
      {
        supplier: 'eBay',
        supplier_sku: 'NEO-NP-06',
        source_url: 'https://www.ebay.co.uk/shop/adax-neo',
        price_basis: 'EX_VAT',
        price_ex_vat: 115.83,
        price_inc_vat: 139.00,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 3. Adax Neo NP 08 KDT
  {
    id: 'erh_adax_neo_np_08_kdt',
    family: 'ERH',
    brand: 'Adax',
    manufacturer: 'Adax (Norway)',
    product_family: 'Neo',
    model: 'Neo NP 08 KDT',
    sku: 'NEO-NP-08',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 0.8,
    rated_output_kw: 0.8,
    output_w_delta_t50: 800,
    height_mm: 370,
    diameter_mm: 704,
    depth_mm: 90,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Digital Timer, Electronic Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://adax.no/en/',
    manufacturer_product_url: 'https://adax.no/en/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'eBay',
    supplier_sku: 'NEO-NP-08',
    price_ex_vat: 130.83,
    price_inc_vat: 157.00,
    price_source_url: 'https://www.ebay.co.uk/itm/152679931340',
    price_date: '2026-09-14',
    notes: 'Adax Neo 800W panel heater. Size 370×704×90mm.',
    prices: [
      {
        supplier: 'eBay',
        supplier_sku: 'NEO-NP-08',
        source_url: 'https://www.ebay.co.uk/itm/152679931340',
        price_basis: 'EX_VAT',
        price_ex_vat: 130.83,
        price_inc_vat: 157.00,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 4. Adax Neo NP 10 KDT
  {
    id: 'erh_adax_neo_np_10_kdt',
    family: 'ERH',
    brand: 'Adax',
    manufacturer: 'Adax (Norway)',
    product_family: 'Neo',
    model: 'Neo NP 10 KDT',
    sku: 'NEO-NP-10',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 1.0,
    rated_output_kw: 1.0,
    output_w_delta_t50: 1000,
    height_mm: 370,
    diameter_mm: 762,
    depth_mm: 90,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Digital Timer, Electronic Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://adax.no/en/',
    manufacturer_product_url: 'https://adax.no/en/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'eBay',
    supplier_sku: 'NEO-NP-10',
    price_ex_vat: 130.83,
    price_inc_vat: 157.00,
    price_source_url: 'https://www.ebay.co.uk/itm/152679931340',
    price_date: '2026-09-14',
    notes: 'Adax Neo 1000W panel heater. Size 370×762×90mm.',
    prices: [
      {
        supplier: 'eBay',
        supplier_sku: 'NEO-NP-10',
        source_url: 'https://www.ebay.co.uk/itm/152679931340',
        price_basis: 'EX_VAT',
        price_ex_vat: 130.83,
        price_inc_vat: 157.00,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 5. Adax Neo NP 12 KDT
  {
    id: 'erh_adax_neo_np_12_kdt',
    family: 'ERH',
    brand: 'Adax',
    manufacturer: 'Adax (Norway)',
    product_family: 'Neo',
    model: 'Neo NP 12 KDT',
    sku: 'NEOL12KWT',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 1.2,
    rated_output_kw: 1.2,
    output_w_delta_t50: 1200,
    height_mm: 370,
    diameter_mm: 934,
    depth_mm: 90,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Digital Timer + WiFi, Electronic WiFi',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://adax.no/en/',
    manufacturer_product_url: 'https://adax.no/en/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Idealo',
    supplier_sku: 'NEOL12KWT',
    price_ex_vat: 184.17,
    price_inc_vat: 221.00,
    price_source_url: 'https://www.idealo.co.uk/compare/208669646/adax-neo-smart-wifi-low-profile-electric-panel-heater-convector-radiator-with-timer-smartphone-control-splash-proof-economic-modern-1200w-white.html',
    price_date: '2026-09-14',
    notes: 'Adax Neo 1200W panel heater with WiFi smartphone control. Size 370×934×90mm.',
    prices: [
      {
        supplier: 'Idealo',
        supplier_sku: 'NEOL12KWT',
        source_url: 'https://www.idealo.co.uk/compare/208669646/adax-neo-smart-wifi-low-profile-electric-panel-heater-convector-radiator-with-timer-smartphone-control-splash-proof-economic-modern-1200w-white.html',
        price_basis: 'EX_VAT',
        price_ex_vat: 184.17,
        price_inc_vat: 221.00,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 6. Adax Neo NP 14 KDT
  {
    id: 'erh_adax_neo_np_14_kdt',
    family: 'ERH',
    brand: 'Adax',
    manufacturer: 'Adax (Norway)',
    product_family: 'Neo',
    model: 'Neo NP 14 KDT',
    sku: 'NEO-NP-14',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 1.4,
    rated_output_kw: 1.4,
    output_w_delta_t50: 1400,
    height_mm: 370,
    diameter_mm: 1042,
    depth_mm: 90,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Digital Timer, Electronic Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://adax.no/en/',
    manufacturer_product_url: 'https://adax.no/en/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'eBay',
    supplier_sku: 'NEO-NP-14',
    price_ex_vat: 151.67,
    price_inc_vat: 182.00,
    price_source_url: 'https://www.ebay.co.uk/b/bn_101771059',
    price_date: '2026-09-14',
    notes: 'Adax Neo 1400W panel heater. Size 370×1042×90mm.',
    prices: [
      {
        supplier: 'eBay',
        supplier_sku: 'NEO-NP-14',
        source_url: 'https://www.ebay.co.uk/b/bn_101771059',
        price_basis: 'EX_VAT',
        price_ex_vat: 151.67,
        price_inc_vat: 182.00,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 7. Adax Neo NP 20 KDT
  {
    id: 'erh_adax_neo_np_20_kdt',
    family: 'ERH',
    brand: 'Adax',
    manufacturer: 'Adax (Norway)',
    product_family: 'Neo',
    model: 'Neo NP 20 KDT',
    sku: 'NCH20KWT',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 2.0,
    rated_output_kw: 2.0,
    output_w_delta_t50: 2000,
    height_mm: 370,
    diameter_mm: 1394,
    depth_mm: 90,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Digital Timer + WiFi, Electronic WiFi',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://adax.no/en/',
    manufacturer_product_url: 'https://adax.no/en/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Quality Heating',
    supplier_sku: 'NCH20KWT',
    price_ex_vat: 165.83,
    price_inc_vat: 199.00,
    price_source_url: 'https://qualityheating.co.uk/products/adax-neo-compact-wifi-modern-electric-convector-heater-white-2000-watts',
    price_date: '2026-09-14',
    notes: 'Adax Neo 2000W panel heater with WiFi smartphone control. Size 370×1394×90mm.',
    prices: [
      {
        supplier: 'Quality Heating',
        supplier_sku: 'NCH20KWT',
        source_url: 'https://qualityheating.co.uk/products/adax-neo-compact-wifi-modern-electric-convector-heater-white-2000-watts',
        price_basis: 'EX_VAT',
        price_ex_vat: 165.83,
        price_inc_vat: 199.00,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 8. Adax Neo NP 25 KDT
  {
    id: 'erh_adax_neo_np_25_kdt',
    family: 'ERH',
    brand: 'Adax',
    manufacturer: 'Adax (Norway)',
    product_family: 'Neo',
    model: 'Neo NP 25 KDT',
    sku: 'NCH25KWT',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 2.5,
    rated_output_kw: 2.5,
    output_w_delta_t50: 2500,
    height_mm: 370,
    diameter_mm: 1678,
    depth_mm: 90,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Digital Timer + WiFi, Electronic WiFi',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://adax.no/en/',
    manufacturer_product_url: 'https://adax.no/en/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Quality Heating',
    supplier_sku: 'NCH25KWT',
    price_ex_vat: 209.17,
    price_inc_vat: 251.00,
    price_source_url: 'https://qualityheating.co.uk/products/adax-neo-compact-wifi-modern-electric-convector-heater-white-2500-watts',
    price_date: '2026-09-14',
    notes: 'Adax Neo 2500W high-output panel heater with WiFi smartphone control. Size 370×1678×90mm.',
    prices: [
      {
        supplier: 'Quality Heating',
        supplier_sku: 'NCH25KWT',
        source_url: 'https://qualityheating.co.uk/products/adax-neo-compact-wifi-modern-electric-convector-heater-white-2500-watts',
        price_basis: 'EX_VAT',
        price_ex_vat: 209.17,
        price_inc_vat: 251.00,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 9. Dimplex PLX050E
  {
    id: 'erh_dimplex_plx050e',
    family: 'ERH',
    brand: 'Dimplex',
    manufacturer: 'Dimplex',
    product_family: 'PLX Series',
    model: 'PLX050E',
    sku: 'PLX050E',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 0.5,
    rated_output_kw: 0.5,
    output_w_delta_t50: 500,
    height_mm: 430,
    diameter_mm: 390,
    depth_mm: 108,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Digital Electronic Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.dimplex.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Heater Shop',
    supplier_sku: 'PLX050E',
    price_ex_vat: 133.32,
    price_inc_vat: 159.98,
    price_source_url: 'https://www.heatershop.co.uk/dimplex-plx050e',
    price_date: '2026-09-14',
    notes: 'Dimplex PLX050E 500W panel heater. Size 430×390×108mm.',
    prices: [
      {
        supplier: 'Heater Shop',
        supplier_sku: 'PLX050E',
        source_url: 'https://www.heatershop.co.uk/dimplex-plx050e',
        price_basis: 'EX_VAT',
        price_ex_vat: 133.32,
        price_inc_vat: 159.98,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 10. Dimplex PLX100E
  {
    id: 'erh_dimplex_plx100e',
    family: 'ERH',
    brand: 'Dimplex',
    manufacturer: 'Dimplex',
    product_family: 'PLX Series',
    model: 'PLX100E',
    sku: 'PLX100E',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 1.0,
    rated_output_kw: 1.0,
    output_w_delta_t50: 1000,
    height_mm: 430,
    diameter_mm: 590,
    depth_mm: 108,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Digital Electronic Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.dimplex.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Heater Shop',
    supplier_sku: 'PLX100E',
    price_ex_vat: 146.02,
    price_inc_vat: 175.22,
    price_source_url: 'https://www.heatershop.co.uk/dimplex-plx100e',
    price_date: '2026-09-14',
    notes: 'Dimplex PLX100E 1000W panel heater. Size 430×590×108mm.',
    prices: [
      {
        supplier: 'Heater Shop',
        supplier_sku: 'PLX100E',
        source_url: 'https://www.heatershop.co.uk/dimplex-plx100e',
        price_basis: 'EX_VAT',
        price_ex_vat: 146.02,
        price_inc_vat: 175.22,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 11. Dimplex PLX150E
  {
    id: 'erh_dimplex_plx150e',
    family: 'ERH',
    brand: 'Dimplex',
    manufacturer: 'Dimplex',
    product_family: 'PLX Series',
    model: 'PLX150E',
    sku: 'PLX150E',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 1.5,
    rated_output_kw: 1.5,
    output_w_delta_t50: 1500,
    height_mm: 430,
    diameter_mm: 690,
    depth_mm: 108,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Digital Electronic Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.dimplex.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'RS Components',
    supplier_sku: 'PLX150E',
    price_ex_vat: 227.71,
    price_inc_vat: 273.25,
    price_source_url: 'https://uk.rs-online.com/web/p/radiators-convection-heaters/1760900',
    price_date: '2026-09-14',
    notes: 'Dimplex PLX150E 1500W panel heater. Size 430×690×108mm.',
    prices: [
      {
        supplier: 'RS Components',
        supplier_sku: 'PLX150E',
        source_url: 'https://uk.rs-online.com/web/p/radiators-convection-heaters/1760900',
        price_basis: 'EX_VAT',
        price_ex_vat: 227.71,
        price_inc_vat: 273.25,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 12. Dimplex PLX200E
  {
    id: 'erh_dimplex_plx200e',
    family: 'ERH',
    brand: 'Dimplex',
    manufacturer: 'Dimplex',
    product_family: 'PLX Series',
    model: 'PLX200E',
    sku: 'PLX200E',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 2.0,
    rated_output_kw: 2.0,
    output_w_delta_t50: 2000,
    height_mm: 430,
    diameter_mm: 890,
    depth_mm: 108,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Digital Electronic Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.dimplex.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Heater Shop',
    supplier_sku: 'PLX200E',
    price_ex_vat: 187.00,
    price_inc_vat: 224.40,
    price_source_url: 'https://www.heatershop.co.uk/',
    price_date: '2026-09-14',
    notes: 'Dimplex PLX200E 2000W panel heater. Size 430×890×108mm.',
    prices: [
      {
        supplier: 'Heater Shop',
        supplier_sku: 'PLX200E',
        source_url: 'https://www.heatershop.co.uk/',
        price_basis: 'EX_VAT',
        price_ex_vat: 187.00,
        price_inc_vat: 224.40,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 13. Haverland iSense 500W
  {
    id: 'erh_haverland_isense_500',
    family: 'ERH',
    brand: 'Haverland',
    manufacturer: 'Haverland',
    product_family: 'iSense',
    model: 'iSense 500W',
    sku: 'ISENSE-500',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 0.5,
    rated_output_kw: 0.5,
    output_w_delta_t50: 500,
    height_mm: 420,
    diameter_mm: 430,
    depth_mm: 85,
    phase: 1,
    electrical_requirements: '230V 1-Phase, WiFi App, Digital WiFi Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.haverland.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'eBay',
    supplier_sku: 'ISENSE-500',
    price_ex_vat: 127.08,
    price_inc_vat: 152.50,
    price_source_url: 'https://www.ebay.co.uk/b/bn_7023406069',
    price_date: '2026-09-14',
    notes: 'Haverland iSense 500W WiFi panel heater. Size 420×430×85mm.',
    prices: [
      {
        supplier: 'eBay',
        supplier_sku: 'ISENSE-500',
        source_url: 'https://www.ebay.co.uk/b/bn_7023406069',
        price_basis: 'EX_VAT',
        price_ex_vat: 127.08,
        price_inc_vat: 152.50,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 14. Haverland iSense 750W
  {
    id: 'erh_haverland_isense_750',
    family: 'ERH',
    brand: 'Haverland',
    manufacturer: 'Haverland',
    product_family: 'iSense',
    model: 'iSense 750W',
    sku: 'ISENSE-750',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 0.75,
    rated_output_kw: 0.75,
    output_w_delta_t50: 750,
    height_mm: 420,
    diameter_mm: 510,
    depth_mm: 85,
    phase: 1,
    electrical_requirements: '230V 1-Phase, WiFi App, Digital WiFi Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.haverland.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'eBay',
    supplier_sku: 'ISENSE-750',
    price_ex_vat: 144.58,
    price_inc_vat: 173.50,
    price_source_url: 'https://www.ebay.co.uk/b/bn_7023406069',
    price_date: '2026-09-14',
    notes: 'Haverland iSense 750W WiFi panel heater. Size 420×510×85mm.',
    prices: [
      {
        supplier: 'eBay',
        supplier_sku: 'ISENSE-750',
        source_url: 'https://www.ebay.co.uk/b/bn_7023406069',
        price_basis: 'EX_VAT',
        price_ex_vat: 144.58,
        price_inc_vat: 173.50,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 15. Haverland iSense 1000W
  {
    id: 'erh_haverland_isense_1000',
    family: 'ERH',
    brand: 'Haverland',
    manufacturer: 'Haverland',
    product_family: 'iSense',
    model: 'iSense 1000W',
    sku: 'ISENSE-1000',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 1.0,
    rated_output_kw: 1.0,
    output_w_delta_t50: 1000,
    height_mm: 420,
    diameter_mm: 555,
    depth_mm: 85,
    phase: 1,
    electrical_requirements: '230V 1-Phase, WiFi App, Digital WiFi Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.haverland.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'eBay',
    supplier_sku: 'ISENSE-1000',
    price_ex_vat: 152.08,
    price_inc_vat: 182.50,
    price_source_url: 'https://www.ebay.co.uk/b/bn_7023406069',
    price_date: '2026-09-14',
    notes: 'Haverland iSense 1000W WiFi panel heater. Size 420×555×85mm.',
    prices: [
      {
        supplier: 'eBay',
        supplier_sku: 'ISENSE-1000',
        source_url: 'https://www.ebay.co.uk/b/bn_7023406069',
        price_basis: 'EX_VAT',
        price_ex_vat: 152.08,
        price_inc_vat: 182.50,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 16. Haverland iSense 1500W
  {
    id: 'erh_haverland_isense_1500',
    family: 'ERH',
    brand: 'Haverland',
    manufacturer: 'Haverland',
    product_family: 'iSense',
    model: 'iSense 1500W',
    sku: 'ISENSE-1500',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 1.5,
    rated_output_kw: 1.5,
    output_w_delta_t50: 1500,
    height_mm: 420,
    diameter_mm: 755,
    depth_mm: 85,
    phase: 1,
    electrical_requirements: '230V 1-Phase, WiFi App, Digital WiFi Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.haverland.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'eBay',
    supplier_sku: 'ISENSE-1500',
    price_ex_vat: 168.75,
    price_inc_vat: 202.50,
    price_source_url: 'https://www.ebay.co.uk/b/bn_7023406069',
    price_date: '2026-09-14',
    notes: 'Haverland iSense 1500W WiFi panel heater. Size 420×755×85mm.',
    prices: [
      {
        supplier: 'eBay',
        supplier_sku: 'ISENSE-1500',
        source_url: 'https://www.ebay.co.uk/b/bn_7023406069',
        price_basis: 'EX_VAT',
        price_ex_vat: 168.75,
        price_inc_vat: 202.50,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 17. Haverland iSense 2000W
  {
    id: 'erh_haverland_isense_2000',
    family: 'ERH',
    brand: 'Haverland',
    manufacturer: 'Haverland',
    product_family: 'iSense',
    model: 'iSense 2000W',
    sku: 'ISENSE-2000',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 2.0,
    rated_output_kw: 2.0,
    output_w_delta_t50: 2000,
    height_mm: 420,
    diameter_mm: 955,
    depth_mm: 85,
    phase: 1,
    electrical_requirements: '230V 1-Phase, WiFi App, Digital WiFi Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.haverland.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'eBay',
    supplier_sku: 'ISENSE-2000',
    price_ex_vat: 184.58,
    price_inc_vat: 221.50,
    price_source_url: 'https://www.ebay.co.uk/b/bn_7023406069',
    price_date: '2026-09-14',
    notes: 'Haverland iSense 2000W WiFi panel heater. Size 420×955×85mm.',
    prices: [
      {
        supplier: 'eBay',
        supplier_sku: 'ISENSE-2000',
        source_url: 'https://www.ebay.co.uk/b/bn_7023406069',
        price_basis: 'EX_VAT',
        price_ex_vat: 184.58,
        price_inc_vat: 221.50,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 18. Stiebel Eltron CNS-U Plus 500W
  {
    id: 'erh_stiebel_cnsu_plus_500',
    family: 'ERH',
    brand: 'Stiebel Eltron',
    manufacturer: 'Stiebel Eltron',
    product_family: 'CNS-U Plus',
    model: 'CNS-U Plus 500W',
    sku: '205867',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 0.5,
    rated_output_kw: 0.5,
    output_w_delta_t50: 500,
    height_mm: 420,
    diameter_mm: 430,
    depth_mm: 85,
    phase: 1,
    electrical_requirements: '230V 1-Phase, LCD Display, Electronic Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.stiebel-eltron.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Alert Electrical',
    supplier_sku: '205867',
    price_ex_vat: 92.25,
    price_inc_vat: 110.70,
    price_source_url: 'https://alertelectrical.com/brands/stiebel_eltron',
    price_date: '2026-09-14',
    notes: 'Stiebel Eltron CNS-U Plus 500W LCD panel heater. Size 420×430×85mm.',
    prices: [
      {
        supplier: 'Alert Electrical',
        supplier_sku: '205867',
        source_url: 'https://alertelectrical.com/brands/stiebel_eltron',
        price_basis: 'EX_VAT',
        price_ex_vat: 92.25,
        price_inc_vat: 110.70,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 19. Stiebel Eltron CNS-U Plus 1000W
  {
    id: 'erh_stiebel_cnsu_plus_1000',
    family: 'ERH',
    brand: 'Stiebel Eltron',
    manufacturer: 'Stiebel Eltron',
    product_family: 'CNS-U Plus',
    model: 'CNS-U Plus 1000W',
    sku: '205868',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 1.0,
    rated_output_kw: 1.0,
    output_w_delta_t50: 1000,
    height_mm: 420,
    diameter_mm: 630,
    depth_mm: 85,
    phase: 1,
    electrical_requirements: '230V 1-Phase, LCD Display, Electronic Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.stiebel-eltron.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Alert Electrical',
    supplier_sku: '205868',
    price_ex_vat: 106.42,
    price_inc_vat: 127.70,
    price_source_url: 'https://alertelectrical.com/heating/electric-panel-heaters.html',
    price_date: '2026-09-14',
    notes: 'Stiebel Eltron CNS-U Plus 1000W LCD panel heater. Size 420×630×85mm.',
    prices: [
      {
        supplier: 'Alert Electrical',
        supplier_sku: '205868',
        source_url: 'https://alertelectrical.com/heating/electric-panel-heaters.html',
        price_basis: 'EX_VAT',
        price_ex_vat: 106.42,
        price_inc_vat: 127.70,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 20. Stiebel Eltron CNS-U Plus 1500W
  {
    id: 'erh_stiebel_cnsu_plus_1500',
    family: 'ERH',
    brand: 'Stiebel Eltron',
    manufacturer: 'Stiebel Eltron',
    product_family: 'CNS-U Plus',
    model: 'CNS-U Plus 1500W',
    sku: '205870',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 1.5,
    rated_output_kw: 1.5,
    output_w_delta_t50: 1500,
    height_mm: 420,
    diameter_mm: 830,
    depth_mm: 85,
    phase: 1,
    electrical_requirements: '230V 1-Phase, LCD Display, Electronic Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.stiebel-eltron.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Alert Electrical',
    supplier_sku: '205870',
    price_ex_vat: 113.95,
    price_inc_vat: 136.74,
    price_source_url: 'https://alertelectrical.com/heating/electric-panel-heaters.html',
    price_date: '2026-09-14',
    notes: 'Stiebel Eltron CNS-U Plus 1500W LCD panel heater. Size 420×830×85mm.',
    prices: [
      {
        supplier: 'Alert Electrical',
        supplier_sku: '205870',
        source_url: 'https://alertelectrical.com/heating/electric-panel-heaters.html',
        price_basis: 'EX_VAT',
        price_ex_vat: 113.95,
        price_inc_vat: 136.74,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 21. Stiebel Eltron CNS-U Plus 2000W
  {
    id: 'erh_stiebel_cnsu_plus_2000',
    family: 'ERH',
    brand: 'Stiebel Eltron',
    manufacturer: 'Stiebel Eltron',
    product_family: 'CNS-U Plus',
    model: 'CNS-U Plus 2000W',
    sku: '205872',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 2.0,
    rated_output_kw: 2.0,
    output_w_delta_t50: 2000,
    height_mm: 420,
    diameter_mm: 1030,
    depth_mm: 85,
    phase: 1,
    electrical_requirements: '230V 1-Phase, LCD Display, Electronic Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.stiebel-eltron.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Alert Electrical',
    supplier_sku: '205872',
    price_ex_vat: 127.29,
    price_inc_vat: 152.75,
    price_source_url: 'https://alertelectrical.com/heating/electric-panel-heaters.html',
    price_date: '2026-09-14',
    notes: 'Stiebel Eltron CNS-U Plus 2000W LCD panel heater. Size 420×1030×85mm.',
    prices: [
      {
        supplier: 'Alert Electrical',
        supplier_sku: '205872',
        source_url: 'https://alertelectrical.com/heating/electric-panel-heaters.html',
        price_basis: 'EX_VAT',
        price_ex_vat: 127.29,
        price_inc_vat: 152.75,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 22. Stiebel Eltron CNS S 500W Trend UK
  {
    id: 'erh_stiebel_cns_500_trend',
    family: 'ERH',
    brand: 'Stiebel Eltron',
    manufacturer: 'Stiebel Eltron',
    product_family: 'CNS Trend',
    model: 'CNS S 500W Trend UK',
    sku: 'CNS-500-TREND',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 0.5,
    rated_output_kw: 0.5,
    output_w_delta_t50: 500,
    height_mm: 420,
    diameter_mm: 430,
    depth_mm: 85,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Manual Electronic Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.stiebel-eltron.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Electrical Wholesalers 4U',
    supplier_sku: 'CNS-500-TREND',
    price_ex_vat: 99.17,
    price_inc_vat: 119.00,
    price_source_url: 'https://electricalwholesalers4u.com/collections/stiebel-eltron',
    price_date: '2026-09-14',
    notes: 'Stiebel Eltron CNS S 500W Trend UK panel heater. Size 420×430×85mm.',
    prices: [
      {
        supplier: 'Electrical Wholesalers 4U',
        supplier_sku: 'CNS-500-TREND',
        source_url: 'https://electricalwholesalers4u.com/collections/stiebel-eltron',
        price_basis: 'EX_VAT',
        price_ex_vat: 99.17,
        price_inc_vat: 119.00,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 23. ThermoSphere Convector Panel 500W
  {
    id: 'erh_thermosphere_panel_500',
    family: 'ERH',
    brand: 'ThermoSphere',
    manufacturer: 'ThermoSphere',
    product_family: 'Convector Panel',
    model: 'Convector Panel 500W',
    sku: 'TS-CP-500W',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 0.5,
    rated_output_kw: 0.5,
    output_w_delta_t50: 500,
    height_mm: 420,
    diameter_mm: 430,
    depth_mm: 85,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Digital Electronic Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.thermosphere.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Trusted Building Supplies',
    supplier_sku: 'TS-CP-500W',
    price_ex_vat: 101.43,
    price_inc_vat: 121.72,
    price_source_url: 'https://trustedbuildingsupplies.co.uk/collections/convector-heaters',
    price_date: '2026-09-14',
    notes: 'ThermoSphere Convector Panel 500W. Size 420×430×85mm.',
    prices: [
      {
        supplier: 'Trusted Building Supplies',
        supplier_sku: 'TS-CP-500W',
        source_url: 'https://trustedbuildingsupplies.co.uk/collections/convector-heaters',
        price_basis: 'EX_VAT',
        price_ex_vat: 101.43,
        price_inc_vat: 121.72,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 24. ThermoSphere Convector Panel 1000W
  {
    id: 'erh_thermosphere_panel_1000',
    family: 'ERH',
    brand: 'ThermoSphere',
    manufacturer: 'ThermoSphere',
    product_family: 'Convector Panel',
    model: 'Convector Panel 1000W',
    sku: 'TS-CP-1000W',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 1.0,
    rated_output_kw: 1.0,
    output_w_delta_t50: 1000,
    height_mm: 420,
    diameter_mm: 630,
    depth_mm: 85,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Digital Electronic Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.thermosphere.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Trusted Building Supplies',
    supplier_sku: 'TS-CP-1000W',
    price_ex_vat: 108.60,
    price_inc_vat: 130.32,
    price_source_url: 'https://trustedbuildingsupplies.co.uk/collections/convector-heaters',
    price_date: '2026-09-14',
    notes: 'ThermoSphere Convector Panel 1000W. Size 420×630×85mm.',
    prices: [
      {
        supplier: 'Trusted Building Supplies',
        supplier_sku: 'TS-CP-1000W',
        source_url: 'https://trustedbuildingsupplies.co.uk/collections/convector-heaters',
        price_basis: 'EX_VAT',
        price_ex_vat: 108.60,
        price_inc_vat: 130.32,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 25. ThermoSphere Convector Panel 1500W
  {
    id: 'erh_thermosphere_panel_1500',
    family: 'ERH',
    brand: 'ThermoSphere',
    manufacturer: 'ThermoSphere',
    product_family: 'Convector Panel',
    model: 'Convector Panel 1500W',
    sku: 'TS-CP-1500W',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 1.5,
    rated_output_kw: 1.5,
    output_w_delta_t50: 1500,
    height_mm: 420,
    diameter_mm: 830,
    depth_mm: 85,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Digital Electronic Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.thermosphere.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Trusted Building Supplies',
    supplier_sku: 'TS-CP-1500W',
    price_ex_vat: 115.77,
    price_inc_vat: 138.92,
    price_source_url: 'https://trustedbuildingsupplies.co.uk/collections/convector-heaters',
    price_date: '2026-09-14',
    notes: 'ThermoSphere Convector Panel 1500W. Size 420×830×85mm.',
    prices: [
      {
        supplier: 'Trusted Building Supplies',
        supplier_sku: 'TS-CP-1500W',
        source_url: 'https://trustedbuildingsupplies.co.uk/collections/convector-heaters',
        price_basis: 'EX_VAT',
        price_ex_vat: 115.77,
        price_inc_vat: 138.92,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 26. ThermoSphere Convector Panel 2000W
  {
    id: 'erh_thermosphere_panel_2000',
    family: 'ERH',
    brand: 'ThermoSphere',
    manufacturer: 'ThermoSphere',
    product_family: 'Convector Panel',
    model: 'Convector Panel 2000W',
    sku: 'TS-CP-2000W',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 2.0,
    rated_output_kw: 2.0,
    output_w_delta_t50: 2000,
    height_mm: 420,
    diameter_mm: 1030,
    depth_mm: 85,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Digital Electronic Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.thermosphere.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Trusted Building Supplies',
    supplier_sku: 'TS-CP-2000W',
    price_ex_vat: 117.42,
    price_inc_vat: 140.90,
    price_source_url: 'https://trustedbuildingsupplies.co.uk/collections/convector-heaters',
    price_date: '2026-09-14',
    notes: 'ThermoSphere Convector Panel 2000W. Size 420×1030×85mm.',
    prices: [
      {
        supplier: 'Trusted Building Supplies',
        supplier_sku: 'TS-CP-2000W',
        source_url: 'https://trustedbuildingsupplies.co.uk/collections/convector-heaters',
        price_basis: 'EX_VAT',
        price_ex_vat: 117.42,
        price_inc_vat: 140.90,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 27. Prem-I-Air Slimline 2kW
  {
    id: 'erh_premiair_slimline_2kw',
    family: 'ERH',
    brand: 'Prem-I-Air',
    manufacturer: 'Prem-I-Air',
    product_family: 'Slimline',
    model: 'Slimline 2kW',
    sku: 'PREM-2KW',
    category: 'Included',
    product_type: 'Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 2.0,
    rated_output_kw: 2.0,
    output_w_delta_t50: 2000,
    height_mm: 450,
    diameter_mm: 900,
    depth_mm: 90,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Digital Electronic Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.premi-air.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'National Heater Shops',
    supplier_sku: 'PREM-2KW',
    price_ex_vat: 90.00,
    price_inc_vat: 108.00,
    price_source_url: 'https://www.nationalheatershops.co.uk/c/office-heaters',
    price_date: '2026-09-14',
    notes: 'Prem-I-Air Slimline 2000W panel heater. Size 450×900×90mm.',
    prices: [
      {
        supplier: 'National Heater Shops',
        supplier_sku: 'PREM-2KW',
        source_url: 'https://www.nationalheatershops.co.uk/c/office-heaters',
        price_basis: 'EX_VAT',
        price_ex_vat: 90.00,
        price_inc_vat: 108.00,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 28. Blyss NDK20-24AF
  {
    id: 'erh_blyss_ndk20_24af',
    family: 'ERH',
    brand: 'Blyss',
    manufacturer: 'Blyss',
    product_family: 'Convector',
    model: 'NDK20-24AF',
    sku: '339RW',
    category: 'Included',
    product_type: 'Portable Convector',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 2.0,
    rated_output_kw: 2.0,
    output_w_delta_t50: 2000,
    height_mm: 440,
    diameter_mm: 615,
    depth_mm: 150,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Manual Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.blyssheating.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Screwfix',
    supplier_sku: '339RW',
    price_ex_vat: 24.96,
    price_inc_vat: 29.95,
    price_source_url: 'https://www.screwfix.com/c/heating-plumbing/heaters/cat831056?heaterfittingtype=portable',
    price_date: '2026-09-14',
    notes: 'Blyss NDK20-24AF 2000W portable convector heater. Size 440×615×150mm.',
    prices: [
      {
        supplier: 'Screwfix',
        supplier_sku: '339RW',
        source_url: 'https://www.screwfix.com/c/heating-plumbing/heaters/cat831056?heaterfittingtype=portable',
        price_basis: 'EX_VAT',
        price_ex_vat: 24.96,
        price_inc_vat: 29.95,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 29. Manrose HP24TIMPH150T
  {
    id: 'erh_manrose_hp24_1500',
    family: 'ERH',
    brand: 'Manrose',
    manufacturer: 'Manrose',
    product_family: 'Panel Heaters',
    model: 'HP24TIMPH150T',
    sku: '5200BTU',
    category: 'Included',
    product_type: 'Wall Panel Heater',
    system_type: 'Direct Electric Space Heating',
    marketing_nominal_kw: 1.5,
    rated_output_kw: 1.5,
    output_w_delta_t50: 1500,
    height_mm: 615,
    diameter_mm: 440,
    depth_mm: 100,
    phase: 1,
    electrical_requirements: '240V 1-Phase, Timer + Thermostat, Wall Mounted',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.manrose.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Screwfix',
    supplier_sku: '5200BTU',
    price_ex_vat: 52.08,
    price_inc_vat: 62.49,
    price_source_url: 'https://www.screwfix.com/c/heating-plumbing/heaters/cat831056?powervoltagesupply=240_v',
    price_date: '2026-09-14',
    notes: 'Manrose 1500W wall panel heater with timer. Size 615×440×100mm.',
    prices: [
      {
        supplier: 'Screwfix',
        supplier_sku: '5200BTU',
        source_url: 'https://www.screwfix.com/c/heating-plumbing/heaters/cat831056?powervoltagesupply=240_v',
        price_basis: 'EX_VAT',
        price_ex_vat: 52.08,
        price_inc_vat: 62.49,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  }
];

// -------------------------------------------------------------
// TABLE 5 — FAN HEATERS MASTER CATALOGUE
// -------------------------------------------------------------
export const RESEARCH_FAN_HEATERS_CATALOG: ProductCatalogItem[] = [
  // 1. Dimplex DXFF20TSN (Multi-supplier: RS Components & Plumb Nation)
  {
    id: 'fan_dimplex_dxff20tsn',
    family: 'FAN_HEATER',
    brand: 'Dimplex',
    manufacturer: 'Dimplex',
    product_family: 'DXFF Series',
    model: 'DXFF20TSN Flat Fan Heater 2kW',
    sku: '6621397',
    category: 'Included',
    product_type: 'Flat Fan Heater',
    system_type: 'Auxiliary Space Heating',
    marketing_nominal_kw: 2.0,
    rated_output_kw: 2.0,
    output_w_delta_t50: 2000,
    height_mm: 114,
    diameter_mm: 253,
    depth_mm: 245,
    phase: 1,
    electrical_requirements: '230V 1-Phase, 20W fan output, Portable, Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.dimplex.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'RS Components',
    supplier_sku: '6621397',
    price_ex_vat: 30.93,
    price_inc_vat: 37.11,
    price_source_url: 'https://uk.rs-online.com/web/p/fan-heaters/6621397',
    price_date: '2026-09-14',
    notes: 'Dimplex DXFF20TSN 2.0kW Flat Fan Heater. Domestic/Office portable use. Size 114×253×245mm.',
    prices: [
      {
        supplier: 'RS Components',
        supplier_sku: '6621397',
        source_url: 'https://uk.rs-online.com/web/p/fan-heaters/6621397',
        price_basis: 'EX_VAT',
        price_ex_vat: 30.93,
        price_inc_vat: 37.11,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      },
      {
        supplier: 'Plumb Nation',
        supplier_sku: '144736',
        source_url: 'https://www.plumbnation.co.uk/dimplex-dxff-flat-fan-heaters-69-14108',
        price_basis: 'EX_VAT',
        price_ex_vat: 33.33,
        price_inc_vat: 40.00,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 2. Dimplex DXFF30TSN (Multi-supplier: RS Components & Plumb Nation)
  {
    id: 'fan_dimplex_dxff30tsn',
    family: 'FAN_HEATER',
    brand: 'Dimplex',
    manufacturer: 'Dimplex',
    product_family: 'DXFF Series',
    model: 'DXFF30TSN Flat Fan Heater 3kW',
    sku: 'DXFF30TSN',
    category: 'Included',
    product_type: 'Flat Fan Heater',
    system_type: 'Auxiliary Space Heating',
    marketing_nominal_kw: 3.0,
    rated_output_kw: 3.0,
    output_w_delta_t50: 3000,
    height_mm: 114,
    diameter_mm: 253,
    depth_mm: 245,
    phase: 1,
    electrical_requirements: '230V 1-Phase, 30W fan output, Portable, Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.dimplex.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'RS Components',
    supplier_sku: 'DXFF30TSN',
    price_ex_vat: 40.69,
    price_inc_vat: 48.83,
    price_source_url: 'https://uk.rs-online.com/web/b/dimplex/',
    price_date: '2026-09-14',
    notes: 'Dimplex DXFF30TSN 3.0kW Flat Fan Heater. Domestic/Office portable use. Size 114×253×245mm.',
    prices: [
      {
        supplier: 'RS Components',
        supplier_sku: 'DXFF30TSN',
        source_url: 'https://uk.rs-online.com/web/b/dimplex/',
        price_basis: 'EX_VAT',
        price_ex_vat: 40.69,
        price_inc_vat: 48.83,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      },
      {
        supplier: 'Plumb Nation',
        supplier_sku: '144737',
        source_url: 'https://www.plumbnation.co.uk/dimplex-dxff-3kw-flat-fan-heater-69-5281',
        price_basis: 'EX_VAT',
        price_ex_vat: 41.67,
        price_inc_vat: 50.00,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 3. Dimplex FX20VE Downflow Fan Heater
  {
    id: 'fan_dimplex_fx20ve',
    family: 'FAN_HEATER',
    brand: 'Dimplex',
    manufacturer: 'Dimplex',
    product_family: 'FX Series',
    model: 'FX20VE Downflow Fan Heater 2kW',
    sku: '4559433',
    category: 'Included',
    product_type: 'Downflow Fan Heater',
    system_type: 'Auxiliary Space Heating',
    marketing_nominal_kw: 2.0,
    rated_output_kw: 2.0,
    output_w_delta_t50: 2000,
    height_mm: 242,
    diameter_mm: 229,
    depth_mm: 109,
    phase: 1,
    electrical_requirements: '230V 1-Phase, 25W fan, Timer + Thermostat, Wall Mount',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.dimplex.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'RS Components',
    supplier_sku: '4559433',
    price_ex_vat: 96.90,
    price_inc_vat: 116.28,
    price_source_url: 'https://uk.rs-online.com/web/p/heaters-radiators/4559433',
    price_date: '2026-09-14',
    notes: 'Dimplex FX20VE commercial high-level wall mounted downflow heater. Size 242×229×109mm.',
    prices: [
      {
        supplier: 'RS Components',
        supplier_sku: '4559433',
        source_url: 'https://uk.rs-online.com/web/p/heaters-radiators/4559433',
        price_basis: 'EX_VAT',
        price_ex_vat: 96.90,
        price_inc_vat: 116.28,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 4. Dimplex FX20EIPX4
  {
    id: 'fan_dimplex_fx20eipx4',
    family: 'FAN_HEATER',
    brand: 'Dimplex',
    manufacturer: 'Dimplex',
    product_family: 'FX Series',
    model: 'FX20EIPX4 Downflow Fan Heater 2kW IPX4',
    sku: '8091607',
    category: 'Included',
    product_type: 'Downflow Fan Heater',
    system_type: 'Auxiliary Space Heating',
    marketing_nominal_kw: 2.0,
    rated_output_kw: 2.0,
    output_w_delta_t50: 2000,
    height_mm: 267,
    diameter_mm: 250,
    depth_mm: 131,
    phase: 1,
    electrical_requirements: '230V 1-Phase, 25W fan, IPX4 splashproof, Wall Mount',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.dimplex.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'RS Components',
    supplier_sku: '8091607',
    price_ex_vat: 116.29,
    price_inc_vat: 139.55,
    price_source_url: 'https://uk.rs-online.com/web/p/heaters-radiators/8091607',
    price_date: '2026-09-14',
    notes: 'Dimplex FX20EIPX4 splashproof downflow heater for bathrooms & commercial washrooms. Size 267×250×131mm.',
    prices: [
      {
        supplier: 'RS Components',
        supplier_sku: '8091607',
        source_url: 'https://uk.rs-online.com/web/p/heaters-radiators/8091607',
        price_basis: 'EX_VAT',
        price_ex_vat: 116.29,
        price_inc_vat: 139.55,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 5. Dimplex RUG3TS
  {
    id: 'fan_dimplex_rug3ts',
    family: 'FAN_HEATER',
    brand: 'Dimplex',
    manufacturer: 'Dimplex',
    product_family: 'Rugged Workshop',
    model: 'RUG3TS Rugged Workshop Fan 3kW',
    sku: 'RUG3TS',
    category: 'Included',
    product_type: 'Rugged Workshop Fan',
    system_type: 'Auxiliary Space Heating',
    marketing_nominal_kw: 3.0,
    rated_output_kw: 3.0,
    output_w_delta_t50: 3000,
    height_mm: 280,
    diameter_mm: 300,
    depth_mm: 250,
    phase: 1,
    electrical_requirements: '230V 1-Phase, 35W fan, dual 1.5kW/3.0kW, Portable',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.dimplex.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Climate Dry',
    supplier_sku: 'RUG3TS',
    price_ex_vat: 74.96,
    price_inc_vat: 89.95,
    price_source_url: 'https://www.climatedry.co.uk/p/dimplex-rug3ts-fan-heater',
    price_date: '2026-09-14',
    notes: 'Dimplex RUG3TS workshop industrial fan heater. Dual 1.5/3.0kW heat settings. Size 280×300×250mm.',
    prices: [
      {
        supplier: 'Climate Dry',
        supplier_sku: 'RUG3TS',
        source_url: 'https://www.climatedry.co.uk/p/dimplex-rug3ts-fan-heater',
        price_basis: 'EX_VAT',
        price_ex_vat: 74.96,
        price_inc_vat: 89.95,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 6. Dimplex Qube 3kW
  {
    id: 'fan_dimplex_qube_3kw',
    family: 'FAN_HEATER',
    brand: 'Dimplex',
    manufacturer: 'Dimplex',
    product_family: 'Qube',
    model: 'Qube 3kW Flat Fan Heater',
    sku: '4153843',
    category: 'Included',
    product_type: 'Flat Fan Heater',
    system_type: 'Auxiliary Space Heating',
    marketing_nominal_kw: 3.0,
    rated_output_kw: 3.0,
    output_w_delta_t50: 3000,
    height_mm: 250,
    diameter_mm: 260,
    depth_mm: 200,
    phase: 1,
    electrical_requirements: '230V 1-Phase, 30W fan, Thermostat, Portable',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.dimplex.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Argos',
    supplier_sku: '4153843',
    price_ex_vat: 83.33,
    price_inc_vat: 100.00,
    price_source_url: 'https://www.argos.co.uk/product/4153843',
    price_date: '2026-09-14',
    notes: 'Dimplex Qube 3kW portable flat domestic convector fan heater. Size 250×260×200mm.',
    prices: [
      {
        supplier: 'Argos',
        supplier_sku: '4153843',
        source_url: 'https://www.argos.co.uk/product/4153843',
        price_basis: 'EX_VAT',
        price_ex_vat: 83.33,
        price_inc_vat: 100.00,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 7. RS PRO 174-6567 (2kW Industrial)
  {
    id: 'fan_rspro_174_6567',
    family: 'FAN_HEATER',
    brand: 'RS PRO',
    manufacturer: 'RS Components Ltd',
    product_family: 'Industrial Fan Heaters',
    model: '174-6567 Industrial Fan Heater 2kW',
    sku: '174-6567',
    category: 'Included',
    product_type: 'Industrial Fan Heater',
    system_type: 'Auxiliary Space Heating',
    marketing_nominal_kw: 2.0,
    rated_output_kw: 2.0,
    output_w_delta_t50: 2000,
    height_mm: 280,
    diameter_mm: 310,
    depth_mm: 260,
    phase: 1,
    electrical_requirements: '230V 1-Phase, 197 m³/h airflow, Floor Mount, Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://uk.rs-online.com/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'RS Components',
    supplier_sku: '174-6567',
    price_ex_vat: 38.25,
    price_inc_vat: 45.90,
    price_source_url: 'https://uk.rs-online.com/web/p/fan-heaters/1746567',
    price_date: '2026-09-14',
    notes: 'RS PRO 2kW heavy-duty industrial fan heater with 197 m³/h airflow rate. Size 280×310×260mm.',
    prices: [
      {
        supplier: 'RS Components',
        supplier_sku: '174-6567',
        source_url: 'https://uk.rs-online.com/web/p/fan-heaters/1746567',
        price_basis: 'EX_VAT',
        price_ex_vat: 38.25,
        price_inc_vat: 45.90,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 8. RS PRO 174-6571 (9kW 3-Phase Industrial)
  {
    id: 'fan_rspro_174_6571',
    family: 'FAN_HEATER',
    brand: 'RS PRO',
    manufacturer: 'RS Components Ltd',
    product_family: 'Industrial Fan Heaters',
    model: '174-6571 Industrial Fan Heater 9kW 3-Phase',
    sku: '174-6571',
    category: 'Included',
    product_type: 'Industrial Fan Heater',
    system_type: 'Auxiliary Space Heating',
    marketing_nominal_kw: 9.0,
    rated_output_kw: 9.0,
    output_w_delta_t50: 9000,
    height_mm: 450,
    diameter_mm: 500,
    depth_mm: 400,
    phase: 3,
    electrical_requirements: '415V 3-Phase, 742 m³/h airflow, Floor Mount, Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://uk.rs-online.com/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'RS Components',
    supplier_sku: '174-6571',
    price_ex_vat: 208.97,
    price_inc_vat: 250.76,
    price_source_url: 'https://uk.rs-online.com/web/c/hvac-fans-thermal-management/heaters-radiators/fan-heaters/',
    price_date: '2026-09-14',
    notes: 'RS PRO 9kW 3-Phase high-capacity industrial fan heater. 742 m³/h airflow. Size 450×500×400mm.',
    prices: [
      {
        supplier: 'RS Components',
        supplier_sku: '174-6571',
        source_url: 'https://uk.rs-online.com/web/c/hvac-fans-thermal-management/heaters-radiators/fan-heaters/',
        price_basis: 'EX_VAT',
        price_ex_vat: 208.97,
        price_inc_vat: 250.76,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 9. Consort CSL1LST
  {
    id: 'fan_consort_csl1lst',
    family: 'FAN_HEATER',
    brand: 'Consort',
    manufacturer: 'Consort Claudgen',
    product_family: 'CSL LST',
    model: 'CSL1LST Wall Fan Heater LST 1kW',
    sku: 'CSL1LST',
    category: 'Included',
    product_type: 'Wall Fan Heater LST',
    system_type: 'Auxiliary Space Heating',
    marketing_nominal_kw: 1.0,
    rated_output_kw: 1.0,
    output_w_delta_t50: 1000,
    height_mm: 360,
    diameter_mm: 590,
    depth_mm: 130,
    phase: 1,
    electrical_requirements: '230V 1-Phase, 35 dBA low noise, NHS/Commercial spec, Wall Mount',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.consort-claudgen.com/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'National Heater Shops',
    supplier_sku: 'CSL1LST',
    price_ex_vat: 151.04,
    price_inc_vat: 181.25,
    price_source_url: 'https://www.nationalheatershops.co.uk/p/consort-csl-lst-fan-heaters',
    price_date: '2026-09-14',
    notes: 'Consort Claudgen Low Surface Temperature (LST) 1kW wall fan heater for healthcare & nurseries. Size 360×590×130mm.',
    prices: [
      {
        supplier: 'National Heater Shops',
        supplier_sku: 'CSL1LST',
        source_url: 'https://www.nationalheatershops.co.uk/p/consort-csl-lst-fan-heaters',
        price_basis: 'EX_VAT',
        price_ex_vat: 151.04,
        price_inc_vat: 181.25,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 10. Consort CSL2LST
  {
    id: 'fan_consort_csl2lst',
    family: 'FAN_HEATER',
    brand: 'Consort',
    manufacturer: 'Consort Claudgen',
    product_family: 'CSL LST',
    model: 'CSL2LST Wall Fan Heater LST 2kW',
    sku: 'CSL2LST',
    category: 'Included',
    product_type: 'Wall Fan Heater LST',
    system_type: 'Auxiliary Space Heating',
    marketing_nominal_kw: 2.0,
    rated_output_kw: 2.0,
    output_w_delta_t50: 2000,
    height_mm: 360,
    diameter_mm: 750,
    depth_mm: 143,
    phase: 1,
    electrical_requirements: '230V 1-Phase, 40 dBA, NHS/Commercial spec, Wall Mount',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.consort-claudgen.com/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'National Heater Shops',
    supplier_sku: 'CSL2LST',
    price_ex_vat: 151.04,
    price_inc_vat: 181.25,
    price_source_url: 'https://www.nationalheatershops.co.uk/p/consort-csl-lst-fan-heaters',
    price_date: '2026-09-14',
    notes: 'Consort Claudgen LST 2kW healthcare wall fan convector. Size 360×750×143mm.',
    prices: [
      {
        supplier: 'National Heater Shops',
        supplier_sku: 'CSL2LST',
        source_url: 'https://www.nationalheatershops.co.uk/p/consort-csl-lst-fan-heaters',
        price_basis: 'EX_VAT',
        price_ex_vat: 151.04,
        price_inc_vat: 181.25,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 11. Consort CSL2MLST
  {
    id: 'fan_consort_csl2mlst',
    family: 'FAN_HEATER',
    brand: 'Consort',
    manufacturer: 'Consort Claudgen',
    product_family: 'CSL LST',
    model: 'CSL2MLST Wall Fan Heater LST 2kW Manual',
    sku: 'CSL2MLST',
    category: 'Included',
    product_type: 'Wall Fan Heater LST',
    system_type: 'Auxiliary Space Heating',
    marketing_nominal_kw: 2.0,
    rated_output_kw: 2.0,
    output_w_delta_t50: 2000,
    height_mm: 360,
    diameter_mm: 750,
    depth_mm: 143,
    phase: 1,
    electrical_requirements: '230V 1-Phase, 40 dBA, Thermostat + Manual controls, Wall Mount',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.consort-claudgen.com/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'National Heater Shops',
    supplier_sku: 'CSL2MLST',
    price_ex_vat: 151.04,
    price_inc_vat: 181.25,
    price_source_url: 'https://www.nationalheatershops.co.uk/p/consort-csl-lst-fan-heaters',
    price_date: '2026-09-14',
    notes: 'Consort Claudgen LST 2kW manual control wall heater. Size 360×750×143mm.',
    prices: [
      {
        supplier: 'National Heater Shops',
        supplier_sku: 'CSL2MLST',
        source_url: 'https://www.nationalheatershops.co.uk/p/consort-csl-lst-fan-heaters',
        price_basis: 'EX_VAT',
        price_ex_vat: 151.04,
        price_inc_vat: 181.25,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 12. Consort CFH3
  {
    id: 'fan_consort_cfh3',
    family: 'FAN_HEATER',
    brand: 'Consort',
    manufacturer: 'Consort Claudgen',
    product_family: 'CFH Series',
    model: 'CFH3 Commercial Fan Heater 3kW',
    sku: 'CFH3',
    category: 'Included',
    product_type: 'Commercial Fan Heater',
    system_type: 'Auxiliary Space Heating',
    marketing_nominal_kw: 3.0,
    rated_output_kw: 3.0,
    output_w_delta_t50: 3000,
    height_mm: 400,
    diameter_mm: 500,
    depth_mm: 300,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Wireless Thermostat Control, Wall/High-level',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.consort-claudgen.com/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Real Shopping',
    supplier_sku: 'CFH3',
    price_ex_vat: 133.33,
    price_inc_vat: 159.99,
    price_source_url: 'https://www.real-shopping.co.uk/product-category/heating/fan-heaters/',
    price_date: '2026-09-14',
    notes: 'Consort CFH3 3.0kW commercial fan heater with wireless thermostat. Size 400×500×300mm.',
    prices: [
      {
        supplier: 'Real Shopping',
        supplier_sku: 'CFH3',
        source_url: 'https://www.real-shopping.co.uk/product-category/heating/fan-heaters/',
        price_basis: 'EX_VAT',
        price_ex_vat: 133.33,
        price_inc_vat: 159.99,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 13. Consort DF2ESL
  {
    id: 'fan_consort_df2esl',
    family: 'FAN_HEATER',
    brand: 'Consort',
    manufacturer: 'Consort Claudgen',
    product_family: 'DF2 Series',
    model: 'DF2ESL Downflow Fan Heater 2kW',
    sku: 'DF2ESL',
    category: 'Included',
    product_type: 'Downflow Fan Heater',
    system_type: 'Auxiliary Space Heating',
    marketing_nominal_kw: 2.0,
    rated_output_kw: 2.0,
    output_w_delta_t50: 2000,
    height_mm: 350,
    diameter_mm: 450,
    depth_mm: 150,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Digital Thermostat, Wall/Downflow',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.consort-claudgen.com/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Real Shopping',
    supplier_sku: 'DF2ESL',
    price_ex_vat: 124.99,
    price_inc_vat: 149.99,
    price_source_url: 'https://www.real-shopping.co.uk/product-category/heating/fan-heaters/',
    price_date: '2026-09-14',
    notes: 'Consort DF2ESL 2kW commercial downflow wall heater with digital controls. Size 350×450×150mm.',
    prices: [
      {
        supplier: 'Real Shopping',
        supplier_sku: 'DF2ESL',
        source_url: 'https://www.real-shopping.co.uk/product-category/heating/fan-heaters/',
        price_basis: 'EX_VAT',
        price_ex_vat: 124.99,
        price_inc_vat: 149.99,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 14. Consort DF2ESL WiFi
  {
    id: 'fan_consort_df2esl_wifi',
    family: 'FAN_HEATER',
    brand: 'Consort',
    manufacturer: 'Consort Claudgen',
    product_family: 'DF2 Series',
    model: 'DF2ESL WiFi Downflow Fan Heater 2kW',
    sku: 'DF2ESL-WIFI',
    category: 'Included',
    product_type: 'Downflow Fan Heater',
    system_type: 'Auxiliary Space Heating',
    marketing_nominal_kw: 2.0,
    rated_output_kw: 2.0,
    output_w_delta_t50: 2000,
    height_mm: 350,
    diameter_mm: 450,
    depth_mm: 150,
    phase: 1,
    electrical_requirements: '230V 1-Phase, WiFi App + Digital Thermostat, Wall/Downflow',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.consort-claudgen.com/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Real Shopping',
    supplier_sku: 'DF2ESL-WIFI',
    price_ex_vat: 133.33,
    price_inc_vat: 159.99,
    price_source_url: 'https://www.real-shopping.co.uk/product-category/heating/fan-heaters/',
    price_date: '2026-09-14',
    notes: 'Consort DF2ESL WiFi 2kW smartphone-controlled downflow heater. Size 350×450×150mm.',
    prices: [
      {
        supplier: 'Real Shopping',
        supplier_sku: 'DF2ESL-WIFI',
        source_url: 'https://www.real-shopping.co.uk/product-category/heating/fan-heaters/',
        price_basis: 'EX_VAT',
        price_ex_vat: 133.33,
        price_inc_vat: 159.99,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 15. deXpro DXPTC2T
  {
    id: 'fan_dexpro_dxptc2t',
    family: 'FAN_HEATER',
    brand: 'deXpro',
    manufacturer: 'deXpro',
    product_family: 'PTC High Level',
    model: 'DXPTC2T PTC High Level Fan 2kW',
    sku: 'DXPTC2T',
    category: 'Included',
    product_type: 'PTC High Level Fan',
    system_type: 'Auxiliary Space Heating',
    marketing_nominal_kw: 2.0,
    rated_output_kw: 2.0,
    output_w_delta_t50: 2000,
    height_mm: 300,
    diameter_mm: 400,
    depth_mm: 150,
    phase: 1,
    electrical_requirements: '230V 1-Phase, PTC Ceramic element, Timer + Remote, High-level Wall',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.dexpro.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Real Shopping',
    supplier_sku: 'DXPTC2T',
    price_ex_vat: 41.66,
    price_inc_vat: 49.99,
    price_source_url: 'https://www.real-shopping.co.uk/product-category/heating/fan-heaters/',
    price_date: '2026-09-14',
    notes: 'deXpro DXPTC2T 2kW high-level PTC ceramic heater with remote control. Size 300×400×150mm.',
    prices: [
      {
        supplier: 'Real Shopping',
        supplier_sku: 'DXPTC2T',
        source_url: 'https://www.real-shopping.co.uk/product-category/heating/fan-heaters/',
        price_basis: 'EX_VAT',
        price_ex_vat: 41.66,
        price_inc_vat: 49.99,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 16. Smith's Caspian Skyline E
  {
    id: 'fan_smiths_caspian_skyline_e',
    family: 'FAN_HEATER',
    brand: "Smith's",
    manufacturer: "Smith's Environmental Products Ltd",
    product_family: 'Caspian',
    model: 'Caspian Skyline E Ceiling Fan Convector 4kW',
    sku: 'CASPIAN-4KW',
    category: 'Included',
    product_type: 'Ceiling Fan Convector',
    system_type: 'Auxiliary Space Heating',
    marketing_nominal_kw: 4.0,
    rated_output_kw: 4.0,
    output_w_delta_t50: 4000,
    height_mm: 600,
    diameter_mm: 600,
    depth_mm: 200,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Ceiling Mounted Commercial/Office, Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://smithsep.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Real Shopping',
    supplier_sku: 'CASPIAN-4KW',
    price_ex_vat: 387.49,
    price_inc_vat: 464.99,
    price_source_url: 'https://www.real-shopping.co.uk/product-category/heating/fan-heaters/',
    price_date: '2026-09-14',
    notes: "Smith's Caspian Skyline E 4.0kW commercial ceiling-mounted fan convector for offices and retail. Size 600×600×200mm.",
    prices: [
      {
        supplier: 'Real Shopping',
        supplier_sku: 'CASPIAN-4KW',
        source_url: 'https://www.real-shopping.co.uk/product-category/heating/fan-heaters/',
        price_basis: 'EX_VAT',
        price_ex_vat: 387.49,
        price_inc_vat: 464.99,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 17. Prem-I-Air 3kW Industrial
  {
    id: 'fan_premiair_3kw_industrial',
    family: 'FAN_HEATER',
    brand: 'Prem-I-Air',
    manufacturer: 'Prem-I-Air',
    product_family: 'Industrial',
    model: '3kW Industrial Fan Heater',
    sku: '3KW-IND',
    category: 'Included',
    product_type: 'Industrial Fan Heater',
    system_type: 'Auxiliary Space Heating',
    marketing_nominal_kw: 3.0,
    rated_output_kw: 3.0,
    output_w_delta_t50: 3000,
    height_mm: 350,
    diameter_mm: 400,
    depth_mm: 300,
    phase: 1,
    electrical_requirements: '230V 1-Phase, 40W fan, dual 1.5kW/3.0kW, Portable',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.premi-air.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'ESE Direct',
    supplier_sku: '3KW-IND',
    price_ex_vat: 74.96,
    price_inc_vat: 89.95,
    price_source_url: 'https://www.esedirect.co.uk/s-381-heaters.aspx',
    price_date: '2026-09-14',
    notes: 'Prem-I-Air 3kW rugged portable industrial fan heater. Dual 1.5/3.0kW settings. Size 350×400×300mm.',
    prices: [
      {
        supplier: 'ESE Direct',
        supplier_sku: '3KW-IND',
        source_url: 'https://www.esedirect.co.uk/s-381-heaters.aspx',
        price_basis: 'EX_VAT',
        price_ex_vat: 74.96,
        price_inc_vat: 89.95,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  },

  // 18. Warmiplan WH-20 (Flagged: No current UK pricing found)
  {
    id: 'fan_warmiplan_wh20',
    family: 'FAN_HEATER',
    brand: 'Warmiplan',
    manufacturer: 'Warmiplan',
    product_family: 'WH Series',
    model: 'Warmiplan WH-20 Fan Convector 2kW',
    sku: 'WH-20',
    category: 'Included',
    product_type: 'Wall Fan Heater',
    system_type: 'Auxiliary Space Heating',
    marketing_nominal_kw: 2.0,
    rated_output_kw: 2.0,
    output_w_delta_t50: 2000,
    height_mm: 300,
    diameter_mm: 400,
    depth_mm: 150,
    phase: 1,
    electrical_requirements: '230V 1-Phase, 20W fan, Wall Mount, Thermostat',
    mcs_status: 'NOT_FOUND',
    verification_status: 'NOT_FOUND',
    manual_review_required: 1,
    supplier: 'NOT FOUND',
    supplier_sku: 'NOT FOUND',
    price_ex_vat: null,
    price_inc_vat: null,
    price_source_url: null,
    price_date: '2026-09-14',
    notes: 'PRICE NOT FOUND: No current UK merchant pricing found during verification pass 14 Sep 2026.',
    conflict_notes: 'PRICE NOT FOUND: Requires direct supplier trade enquiry.',
    prices: []
  },

  // 19. Blyss NDK20-24AF (Portable Convector Fan)
  {
    id: 'fan_blyss_ndk20_24af',
    family: 'FAN_HEATER',
    brand: 'Blyss',
    manufacturer: 'Blyss',
    product_family: 'Convector',
    model: 'NDK20-24AF Portable Convector 2kW',
    sku: '339RW',
    category: 'Included',
    product_type: 'Portable Convector',
    system_type: 'Auxiliary Space Heating',
    marketing_nominal_kw: 2.0,
    rated_output_kw: 2.0,
    output_w_delta_t50: 2000,
    height_mm: 440,
    diameter_mm: 615,
    depth_mm: 150,
    phase: 1,
    electrical_requirements: '230V 1-Phase, Portable, Manual Thermostat',
    mcs_status: 'NOT_FOUND',
    manufacturer_url: 'https://www.blyssheating.co.uk/',
    verification_status: 'VERIFIED',
    manual_review_required: 0,
    supplier: 'Screwfix',
    supplier_sku: '339RW',
    price_ex_vat: 24.96,
    price_inc_vat: 29.95,
    price_source_url: 'https://www.screwfix.com/c/heating-plumbing/heaters/cat831056?heaterfittingtype=portable',
    price_date: '2026-09-14',
    notes: 'Blyss NDK20-24AF portable domestic convector fan heater. Size 440×615×150mm.',
    prices: [
      {
        supplier: 'Screwfix',
        supplier_sku: '339RW',
        source_url: 'https://www.screwfix.com/c/heating-plumbing/heaters/cat831056?heaterfittingtype=portable',
        price_basis: 'EX_VAT',
        price_ex_vat: 24.96,
        price_inc_vat: 29.95,
        vat_rate: 0.0,
        price_date: '2026-09-14',
        confidence: 'MARKET_CONFIRMED'
      }
    ]
  }
];
