import { db } from './connection.js';

export async function initSubmissionsTables() {
  // 1. Submissions Table
  await db.exec(`
    CREATE TABLE IF NOT EXISTS submissions (
      id TEXT PRIMARY KEY,
      job_reference TEXT NOT NULL UNIQUE,
      lead_id TEXT,
      customer_name TEXT NOT NULL,
      customer_email TEXT,
      customer_phone TEXT,
      property_address TEXT NOT NULL,
      postcode TEXT,
      country TEXT DEFAULT 'England',
      technology TEXT DEFAULT 'Air-to-water heat pump',
      property_status TEXT DEFAULT 'Existing property',
      on_off_gas_grid TEXT DEFAULT 'On gas grid',
      existing_fuel TEXT DEFAULT 'Mains Gas',
      cylinder_applicable INTEGER DEFAULT 1,
      installation_date DATE,
      commissioning_date DATE,
      bus_voucher_reference TEXT,
      bus_voucher_expiry DATE,
      mcs_certificate_number TEXT,
      grant_category TEXT DEFAULT '£7,500 Standard AWHP/GSHP',
      current_stage TEXT DEFAULT '01 Eligibility',
      overall_status TEXT DEFAULT 'Pending',
      completion_percentage REAL DEFAULT 0.0,
      next_action TEXT DEFAULT 'Complete pre-check eligibility',
      assigned_to TEXT,
      notes TEXT,
      six_year_retention_date DATE,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );
  `);

  // 2. Submission Requirement Items Table
  await db.exec(`
    CREATE TABLE IF NOT EXISTS submission_items (
      id TEXT PRIMARY KEY,
      submission_id TEXT NOT NULL,
      stage_code TEXT NOT NULL,
      stage_name TEXT NOT NULL,
      section_name TEXT NOT NULL,
      requirement_key TEXT NOT NULL,
      title TEXT NOT NULL,
      short_description TEXT,
      what_is_this TEXT,
      why_required TEXT,
      who_completes TEXT,
      who_submits TEXT,
      customer_signature_type TEXT DEFAULT 'No signature',
      classification TEXT DEFAULT 'OFFICIAL',
      status TEXT DEFAULT 'Pending',
      is_conditional INTEGER DEFAULT 0,
      condition_rule TEXT,
      due_date DATE,
      completed_date DATE,
      responsible_person TEXT,
      reviewer_person TEXT,
      evidence_required TEXT,
      reference_number TEXT,
      notes TEXT,
      authority TEXT,
      source_url TEXT,
      document_version TEXT,
      clause_page TEXT,
      last_verified_date DATE,
      sort_order INTEGER DEFAULT 0,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE
    );
  `);

  // 3. Submission Evidence Files Table
  await db.exec(`
    CREATE TABLE IF NOT EXISTS submission_evidence (
      id TEXT PRIMARY KEY,
      submission_id TEXT NOT NULL,
      item_id TEXT NOT NULL,
      file_name TEXT NOT NULL,
      file_type TEXT,
      file_size INTEGER,
      file_path_or_url TEXT NOT NULL,
      reference_no TEXT,
      uploaded_by TEXT,
      notes TEXT,
      uploaded_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE,
      FOREIGN KEY (item_id) REFERENCES submission_items(id) ON DELETE CASCADE
    );
  `);

  // 4. Submission Audit Logs Table
  await db.exec(`
    CREATE TABLE IF NOT EXISTS submission_audit_logs (
      id TEXT PRIMARY KEY,
      submission_id TEXT NOT NULL,
      item_id TEXT,
      user_id TEXT,
      user_name TEXT,
      field_changed TEXT NOT NULL,
      old_value TEXT,
      new_value TEXT,
      notes TEXT,
      changed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE
    );
  `);
}

// Master Requirement Item Definitions from Submission Requirements & Evidence Master Guide
export const MASTER_REQUIREMENTS_TEMPLATE = [
  // STAGE 01: ELIGIBILITY
  {
    stage_code: '01_eligibility',
    stage_name: '01 Eligibility',
    section_name: 'Property',
    requirement_key: 'req_customer_lead',
    title: 'Customer Contact & Job Details',
    short_description: 'Customer name, contact details, job reference and property location.',
    what_is_this: 'Internal Prime Energy lead and job record establishing basic identity and location.',
    why_required: 'Baseline record required for workflow, legal ownership checks, and Ofgem application mapping.',
    who_completes: 'Sales / Admin',
    who_submits: 'Internal Prime Energy Workflow',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'Prime Energy / Ofgem',
    source_url: 'https://www.ofgem.gov.uk/sites/default/files/2026-07/boiler_upgrade_scheme_guidance_for_installers_v5.1_20260630135616-20260701135531.pdf',
    clause_page: 'V5.1 §3.1',
    evidence_required: 'Lead record summary, property address proof',
    sort_order: 1
  },
  {
    stage_code: '01_eligibility',
    stage_name: '01 Eligibility',
    section_name: 'Ownership',
    requirement_key: 'req_property_ownership',
    title: 'Property Ownership Evidence',
    short_description: 'Land Registry title or deeds verifying legal owner name and property status.',
    what_is_this: 'Official document proving the applicant is the legal owner of the property.',
    why_required: 'BUS rules require the property owner to become the legal owner of the funded heating system and confirm consent.',
    who_completes: 'Customer / Property Owner',
    who_submits: 'Installer to Ofgem',
    customer_signature_type: 'Ofgem electronic consent',
    classification: 'OFFICIAL',
    authority: 'Ofgem BUS Regulations 2022',
    source_url: 'https://www.legislation.gov.uk/uksi/2022/565/body',
    clause_page: 'Regulation 5',
    evidence_required: 'Land Registry Title Deed, mortgage statement, or power of attorney document',
    sort_order: 2
  },
  {
    stage_code: '01_eligibility',
    stage_name: '01 Eligibility',
    section_name: 'Existing Heating',
    requirement_key: 'req_existing_heating',
    title: 'Existing Heating System & Fossil Fuel Replacement',
    short_description: 'Details of existing heating system (gas, oil, LPG, electric) and replacement plan.',
    what_is_this: 'Record verifying that an existing fossil-fuel or direct electric system is being fully replaced.',
    why_required: 'BUS is primarily for existing buildings replacing fossil fuels. System cannot normally remain alongside heat pump.',
    who_completes: 'Surveyor / Sales',
    who_submits: 'Installer to Ofgem',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'Ofgem BUS Guidance V5.1',
    source_url: 'https://www.ofgem.gov.uk/sites/default/files/2026-07/boiler_upgrade_scheme_guidance_for_installers_v5.1_20260630135616-20260701135531.pdf',
    clause_page: 'V5.1 §4.2',
    evidence_required: 'Boiler photos, fuel type confirmation, survey record',
    sort_order: 3
  },
  {
    stage_code: '01_eligibility',
    stage_name: '01 Eligibility',
    section_name: 'Gas Grid',
    requirement_key: 'req_gas_grid',
    title: 'Gas Grid Connection Status',
    short_description: 'Verification of whether the property is connected to mains gas grid.',
    what_is_this: 'Check confirming on-gas vs off-gas grid status.',
    why_required: 'Determines whether project qualifies for standard £7,500 grant or conditional £9,000 off-gas uplift.',
    who_completes: 'Surveyor',
    who_submits: 'Installer to Ofgem',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'GOV.UK BUS Approved Standards',
    source_url: 'https://www.gov.uk/government/publications/boiler-upgrade-scheme-regulations-approved-standards-grant-categories-and-grant-levels',
    clause_page: 'Grant Categories 2026',
    evidence_required: 'Utility check, gas meter inspection, or survey record',
    sort_order: 4
  },
  {
    stage_code: '01_eligibility',
    stage_name: '01 Eligibility',
    section_name: 'Funding',
    requirement_key: 'req_prior_funding',
    title: 'Prior Public Funding Check',
    short_description: 'Declaration confirming no previous BUS or domestic RHI grant claimed for property.',
    what_is_this: 'Declaration and database lookup for prior public heating grants.',
    why_required: 'Statutory rule preventing duplicate public funding on the same property.',
    who_completes: 'Customer / Sales',
    who_submits: 'Installer to Ofgem',
    customer_signature_type: 'Customer signature',
    classification: 'OFFICIAL',
    authority: 'BUS Regulations 2022',
    source_url: 'https://www.legislation.gov.uk/uksi/2022/565/body',
    clause_page: 'Regulation 12',
    evidence_required: 'Signed customer funding declaration',
    sort_order: 5
  },
  {
    stage_code: '01_eligibility',
    stage_name: '01 Eligibility',
    section_name: 'EPC',
    requirement_key: 'req_epc_certificate',
    title: 'Energy Performance Certificate (EPC)',
    short_description: 'Valid domestic EPC reference number and certificate document.',
    what_is_this: 'Government EPC rating and floor area baseline document.',
    why_required: 'Used for property eligibility validation and heat loss heuristic cross-check.',
    who_completes: 'Surveyor / Sales',
    who_submits: 'Installer to Ofgem',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'GOV.UK SAP Guidance',
    source_url: 'https://www.gov.uk/guidance/standard-assessment-procedure',
    clause_page: 'EPC Methodology',
    evidence_required: 'EPC PDF certificate, reference number lookup',
    sort_order: 6
  },
  {
    stage_code: '01_eligibility',
    stage_name: '01 Eligibility',
    section_name: 'BUS Category',
    requirement_key: 'req_bus_precheck',
    title: 'Internal BUS Eligibility Assessment',
    short_description: 'Preliminary check of property location, technology, and expected grant category.',
    what_is_this: 'Internal Prime Energy eligibility checklist completed before formal quotation.',
    why_required: 'Ensures system design and pricing match scheme eligibility parameters.',
    who_completes: 'Sales / BUS Administrator',
    who_submits: 'Internal',
    customer_signature_type: 'No signature',
    classification: 'PRIME ENERGY INTERNAL',
    authority: 'Prime Energy Config',
    source_url: 'Internal Quality System',
    clause_page: 'BUS Pre-check §1',
    evidence_required: 'Completed BUS pre-check summary form',
    sort_order: 7
  },

  // STAGE 02: PRE-INSTALLATION
  {
    stage_code: '02_pre_installation',
    stage_name: '02 Pre-Installation',
    section_name: 'Quote',
    requirement_key: 'req_itemised_quote',
    title: 'Itemised BUS Quotation',
    short_description: 'Quote displaying gross price, upfront BUS grant deduction (£7.5k/£9k), and net payable amount.',
    what_is_this: 'Formal itemised customer quotation passing on full BUS grant discount upfront.',
    why_required: 'Legal BUS requirement that the grant must be deducted upfront from customer quote.',
    who_completes: 'Estimator / Sales',
    who_submits: 'Installer to Customer',
    customer_signature_type: 'Customer signature',
    classification: 'OFFICIAL',
    authority: 'Ofgem Property Owner Guidance V5.1',
    source_url: 'https://www.ofgem.gov.uk/sites/default/files/2026-07/boiler_upgrade_scheme_guidance_for_property_owners_v5.1_20260630134104-20260701140218.pdf',
    clause_page: 'V5.1 §§4.16–4.19',
    evidence_required: 'Itemised quotation PDF with explicit BUS discount line',
    sort_order: 8
  },
  {
    stage_code: '02_pre_installation',
    stage_name: '02 Pre-Installation',
    section_name: 'Contract',
    requirement_key: 'req_customer_contract',
    title: 'Installation Contract',
    short_description: 'Executed installation contract specifying scope, terms, warranty, and payment schedule.',
    what_is_this: 'Binding contract between Prime Energy and customer.',
    why_required: 'Establishes consumer protection, payment terms, and installation agreement.',
    who_completes: 'Sales / Customer',
    who_submits: 'Internal Contract File',
    customer_signature_type: 'Customer signature',
    classification: 'PRIME ENERGY INTERNAL',
    authority: 'Consumer Rights Act 2015',
    source_url: 'https://mcscertified.com',
    clause_page: 'Consumer Code Standard',
    evidence_required: 'Signed customer contract PDF',
    sort_order: 9
  },
  {
    stage_code: '02_pre_installation',
    stage_name: '02 Pre-Installation',
    section_name: 'Consumer/code requirements',
    requirement_key: 'req_consumer_code_notice',
    title: 'Consumer Code & Privacy Notice',
    short_description: 'RECC or HIES consumer protection notice and privacy statement provided to customer.',
    what_is_this: 'Mandatory consumer code disclosure sheet.',
    why_required: 'Required by MCS consumer protection rules.',
    who_completes: 'Sales',
    who_submits: 'Customer',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'RECC / HIES Consumer Code',
    source_url: 'https://www.recc.org.uk',
    clause_page: 'Consumer Protection §4',
    evidence_required: 'Signed or delivered consumer code acknowledgement',
    sort_order: 10
  },
  {
    stage_code: '02_pre_installation',
    stage_name: '02 Pre-Installation',
    section_name: 'Planning',
    requirement_key: 'req_planning_permitted',
    title: 'Planning Permission & MCS 020 Sound Assessment',
    short_description: 'Assessment showing heat pump meets Permitted Development rules (MCS 020 noise limits) or planning consent.',
    what_is_this: 'MCS 020 noise calculation sheet or local authority planning grant.',
    why_required: 'Statutory compliance with town planning noise restrictions.',
    who_completes: 'Designer / Surveyor',
    who_submits: 'Internal / Planning Authority',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'MCS 020 Sound Assessment',
    source_url: 'https://mcscertified.com/wp-content/uploads/2021/10/MCS-020.pdf',
    clause_page: 'MCS 020 Procedure',
    evidence_required: 'MCS 020 calculation sheet or planning approval certificate',
    sort_order: 11
  },
  {
    stage_code: '02_pre_installation',
    stage_name: '02 Pre-Installation',
    section_name: 'Building regulations',
    requirement_key: 'req_building_regs_route',
    title: 'Building Regulations Route Confirmation',
    short_description: 'Strategy for Building Regulations compliance (Competent Person Scheme vs Building Control).',
    what_is_this: 'Compliance route record for building notification.',
    why_required: 'Statutory obligation for heating and electrical works.',
    who_completes: 'Installer / Project Manager',
    who_submits: 'Competent Person Scheme',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'Building Regulations 2010',
    source_url: 'https://www.gov.uk/building-regulations-approval',
    clause_page: 'Part L / Part P',
    evidence_required: 'CPS registration plan or building control submission',
    sort_order: 12
  },

  // STAGE 03: SURVEY
  {
    stage_code: '03_survey',
    stage_name: '03 Survey',
    section_name: 'Site survey',
    requirement_key: 'req_site_survey_record',
    title: 'Comprehensive Site Survey Record',
    short_description: 'Complete survey documenting room dimensions, emitters, boiler, electrical supply, and pipework.',
    what_is_this: 'Survey checklist capturing all physical property parameters.',
    why_required: 'Provides required empirical input for heat loss calculation and system engineering.',
    who_completes: 'Competent Surveyor',
    who_submits: 'Internal Design File',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'MCS MIS 3005-D',
    source_url: 'https://mcscertified.com',
    clause_page: 'Survey Protocol',
    evidence_required: 'Completed site survey form PDF',
    sort_order: 13
  },
  {
    stage_code: '03_survey',
    stage_name: '03 Survey',
    section_name: 'Existing system',
    requirement_key: 'req_existing_heat_photos',
    title: 'Existing Boiler & Fuel System Photos',
    short_description: 'Photographs of existing boiler rating plate, fuel connection, and installation position.',
    what_is_this: 'Dated photographic evidence of existing fossil heating unit.',
    why_required: 'Audit evidence supporting existing fossil fuel replacement condition.',
    who_completes: 'Surveyor',
    who_submits: 'Internal Audit File',
    customer_signature_type: 'No signature',
    classification: 'PRIME ENERGY INTERNAL',
    authority: 'Ofgem Audit Protocol',
    source_url: 'https://www.ofgem.gov.uk',
    clause_page: 'Audit Evidence §2',
    evidence_required: 'Dated photos of boiler rating plate, flue, and boiler room',
    sort_order: 14
  },
  {
    stage_code: '03_survey',
    stage_name: '03 Survey',
    section_name: 'Radiators/emitter information',
    requirement_key: 'req_emitter_survey_data',
    title: 'Existing Radiator & Emitter Schedule',
    short_description: 'Room-by-room count, types (K1, P+, K2), dimensions, and Stelrad Δt30 output capacity.',
    what_is_this: 'Inventory of existing radiators and estimated capacity.',
    why_required: 'Used to check if existing radiators deliver required kW output at low heat pump flow temps (55°C/45°C).',
    who_completes: 'Surveyor',
    who_submits: 'Designer',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'Stelrad Δt30 Data / MIS 3005-D',
    source_url: 'https://mcscertified.com',
    clause_page: 'MIS 3005-D §5.5',
    evidence_required: 'Radiator schedule table and dimensions log',
    sort_order: 15
  },
  {
    stage_code: '03_survey',
    stage_name: '03 Survey',
    section_name: 'Electrical',
    requirement_key: 'req_electrical_survey',
    title: 'Electrical Supply & Consumer Unit Assessment',
    short_description: 'Inspection of main service fuse rating, consumer unit capacity, RCD protection, and earthing.',
    what_is_this: 'Electrical site assessment record.',
    why_required: 'Ensures electrical infrastructure supports heat pump compressor and immersion heater demand.',
    who_completes: 'Surveyor / Electrician',
    who_submits: 'Internal',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'BS 7671 IET Wiring Regs',
    source_url: 'https://theiet.org',
    clause_page: 'Part 7 Special Locations',
    evidence_required: 'Consumer unit photo, main fuse rating photo, EICR where available',
    sort_order: 16
  },
  {
    stage_code: '03_survey',
    stage_name: '03 Survey',
    section_name: 'Hydraulic',
    requirement_key: 'req_hydraulic_survey',
    title: 'Hydraulic & Pipework Assessment',
    short_description: 'Assessment of main flow/return pipe sizes (15mm vs microbore 10mm or less).',
    what_is_this: 'Pipework inspection report.',
    why_required: 'Detects microbore pipework which requires full re-pipe to prevent flow velocity restrictions.',
    who_completes: 'Surveyor',
    who_submits: 'Internal',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'Prime Energy Hydraulic Engine',
    source_url: 'Internal Standard',
    clause_page: 'Hydraulic Protocol §3',
    evidence_required: 'Pipe diameter photos and flow route notes',
    sort_order: 17
  },

  // STAGE 04: DESIGN
  {
    stage_code: '04_design',
    stage_name: '04 Design',
    section_name: 'Room-by-room heat loss',
    requirement_key: 'req_heat_loss_calc',
    title: 'Room-by-Room Heat Loss Calculation (BS EN 12831-1)',
    short_description: 'MCS-compliant room-by-room heat loss calculation following BS EN 12831-1:2017.',
    what_is_this: 'Official design heat loss calculation determining exact kW load for every heated room.',
    why_required: 'Mandatory MCS requirement; annual EPC kWh must NEVER be substituted for design peak heat loss.',
    who_completes: 'Certified Heat Pump Designer',
    who_submits: 'MCS Design File',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'MIS 3005-D:2025 V2.0 §5.5.1',
    source_url: 'https://mcscertified.com/wp-content/uploads/2025/12/MIS-3005-D-2025-V2.0-Final.pdf',
    clause_page: 'MIS 3005-D §5.5.1(a), p.13',
    evidence_required: 'Full BS EN 12831 room-by-room calculation report PDF',
    sort_order: 18
  },
  {
    stage_code: '04_design',
    stage_name: '04 Design',
    section_name: 'Design temperatures',
    requirement_key: 'req_design_temps',
    title: 'Internal & External Design Temperature Schedule',
    short_description: 'Record of internal room temperatures (MIS 3005-D Table 1) and external design temperature (Table 2).',
    what_is_this: 'Design temperature parameter log.',
    why_required: 'Ensures heat loss calculation complies with standard regional design conditions.',
    who_completes: 'Designer',
    who_submits: 'Internal',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'MIS 3005-D Tables 1 & 2',
    source_url: 'https://mcscertified.com/wp-content/uploads/2025/12/MIS-3005-D-2025-V2.0-Final.pdf',
    clause_page: 'Table 1 & Table 2, p.15',
    evidence_required: 'Design temperature schedule sheet',
    sort_order: 19
  },
  {
    stage_code: '04_design',
    stage_name: '04 Design',
    section_name: 'Heat pump selection',
    requirement_key: 'req_heat_pump_selection',
    title: 'Heat Pump Selection & Sizing Evidence',
    short_description: 'Verification that selected ASHP rated output at design condition provides >=100% of peak heat loss.',
    what_is_this: 'Product selection sheet matching heat pump rated kW to design heat loss.',
    why_required: 'Sizing must be based on certified rated output at design ambient (-2°C/45°C), not marketing nominal kW.',
    who_completes: 'Designer',
    who_submits: 'Installer to MCS',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'MIS 3005-D §5.5.1(e)',
    source_url: 'https://mcscertified.com/wp-content/uploads/2025/12/MIS-3005-D-2025-V2.0-Final.pdf',
    clause_page: '§5.5.1(e), p.14',
    evidence_required: 'Manufacturer performance datasheet and selection justification',
    sort_order: 20
  },
  {
    stage_code: '04_design',
    stage_name: '04 Design',
    section_name: 'MCS 031',
    requirement_key: 'req_mcs_031_estimate',
    title: 'MCS 031 Pre-Sale Performance Estimate',
    short_description: 'MCS 031 estimate providing SCOP, annual space/water heating kWh, and running cost forecast.',
    what_is_this: 'Pre-sale performance estimate report calculated using the official MCS 031 tool.',
    why_required: 'Mandatory pre-sale disclosure provided to customer prior to contract sign-off.',
    who_completes: 'Designer / Estimator',
    who_submits: 'Customer',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'MCS 031 Standard',
    source_url: 'https://mcscertified.com/an-update-to-mcs-031-the-heat-pump-pre-sale-information-and-performance-calculation/',
    clause_page: 'MCS 031 Calculation Method',
    evidence_required: 'MCS 031 performance calculation sheet PDF',
    sort_order: 21
  },
  {
    stage_code: '04_design',
    stage_name: '04 Design',
    section_name: 'Cylinder/DHW design',
    requirement_key: 'req_cylinder_dhw_design',
    title: 'Hot Water Cylinder & DHW System Design',
    short_description: 'Calculation of cylinder storage volume, coil recovery, primary flow temp, and legionella cycle.',
    what_is_this: 'DHW design specification.',
    why_required: 'Ensures hot water cylinder capacity complies with occupancy rules (CIBSE / BS 6700).',
    who_completes: 'Designer',
    who_submits: 'Internal',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'CIBSE Guide G / BS 6700',
    source_url: 'https://www.cibse.org',
    clause_page: 'DHW Storage Sizing',
    evidence_required: 'Cylinder datasheet, coil area verification, legionella strategy',
    sort_order: 22,
    is_conditional: 1,
    condition_rule: 'CYLINDER_ONLY'
  },
  {
    stage_code: '04_design',
    stage_name: '04 Design',
    section_name: 'Hydraulic design',
    requirement_key: 'req_gshp_ground_loop',
    title: 'Ground Heat Exchanger Design (GSHP Only)',
    short_description: 'Completed ground loop borehole/trench design calculations according to MIS 3005.',
    what_is_this: 'Ground loop engineering design file.',
    why_required: 'Mandatory for Ground-Source Heat Pump installations.',
    who_completes: 'Specialist GSHP Designer',
    who_submits: 'MCS / Handover Pack',
    customer_signature_type: 'No signature',
    classification: 'CONDITIONAL',
    authority: 'MIS 3005 Ground Heat Exchanger Standard',
    source_url: 'https://mcscertified.com',
    clause_page: 'MIS 3005 GSHP §6',
    evidence_required: 'Ground loop layout drawing, pipe length, pressure drop calculations',
    sort_order: 23,
    is_conditional: 1,
    condition_rule: 'GSHP_ONLY'
  },

  // STAGE 05: CUSTOMER DOCUMENTS
  {
    stage_code: '05_customer_documents',
    stage_name: '05 Customer Documents',
    section_name: 'Quote acceptance',
    requirement_key: 'req_quote_acceptance',
    title: 'Customer Quotation Acceptance',
    short_description: 'Customer accepted quotation displaying agreed gross price and upfront BUS grant discount.',
    what_is_this: 'Signed or approved quotation copy.',
    why_required: 'Confirms customer acceptance of price and upfront grant deduction.',
    who_completes: 'Customer',
    who_submits: 'Sales',
    customer_signature_type: 'Customer signature',
    classification: 'PRIME ENERGY INTERNAL',
    authority: 'Prime Energy Contracting',
    source_url: 'Internal Policy',
    clause_page: 'Quote Acceptance §2',
    evidence_required: 'Signed quote acceptance copy',
    sort_order: 24
  },
  {
    stage_code: '05_customer_documents',
    stage_name: '05 Customer Documents',
    section_name: 'BUS consent',
    requirement_key: 'req_bus_owner_consent',
    title: 'Ofgem BUS Property Owner Consent',
    short_description: 'Confirmation that property owner completed Ofgem electronic consent and identity verification.',
    what_is_this: 'Ofgem portal consent receipt.',
    why_required: 'Mandatory for BUS voucher application to be properly made by Ofgem.',
    who_completes: 'Property Owner',
    who_submits: 'Installer to Ofgem Portal',
    customer_signature_type: 'Ofgem electronic consent',
    classification: 'OFFICIAL',
    authority: 'Ofgem BUS Property Owner Guidance V5.1',
    source_url: 'https://www.ofgem.gov.uk/sites/default/files/2026-07/boiler_upgrade_scheme_guidance_for_property_owners_v5.1_20260630134104-20260701140218.pdf',
    clause_page: 'V5.1 §3',
    evidence_required: 'Ofgem portal owner consent confirmation receipt',
    sort_order: 25
  },
  {
    stage_code: '05_customer_documents',
    stage_name: '05 Customer Documents',
    section_name: 'Self-build evidence where applicable',
    requirement_key: 'req_self_build_evidence',
    title: 'Self-Build Ownership & Planning Evidence',
    short_description: 'Planning permission, building control completion, or title deed confirming self-build status.',
    what_is_this: 'Self-build proof documents.',
    why_required: 'Required for self-build properties qualifying under BUS rules.',
    who_completes: 'Property Owner / Sales',
    who_submits: 'Installer to Ofgem',
    customer_signature_type: 'No signature',
    classification: 'CONDITIONAL',
    authority: 'Ofgem BUS Installer Guidance V5.1',
    source_url: 'https://www.ofgem.gov.uk',
    clause_page: 'Self-build Eligibility §4.5',
    evidence_required: 'Building control notice, planning approval, title deed',
    sort_order: 26,
    is_conditional: 1,
    condition_rule: 'SELF_BUILD_ONLY'
  },
  {
    stage_code: '05_customer_documents',
    stage_name: '05 Customer Documents',
    section_name: 'Off-gas evidence where applicable',
    requirement_key: 'req_off_gas_uplift_evidence',
    title: '£9,000 Off-Gas Uplift Evidence (Oil/LPG Replacement)',
    short_description: 'Evidence confirming property is off gas grid and replacing existing oil or LPG heating system.',
    what_is_this: 'Fuel tank photos, fuel delivery bills, and off-gas verification.',
    why_required: 'Required to claim the higher £9,000 grant uplift.',
    who_completes: 'Surveyor / Owner',
    who_submits: 'Installer to Ofgem',
    customer_signature_type: 'No signature',
    classification: 'CONDITIONAL',
    authority: 'Ofgem BUS Guidance V5.1 (Uplift Category)',
    source_url: 'https://www.ofgem.gov.uk/sites/default/files/2026-07/boiler_upgrade_scheme_guidance_for_installers_v5.1_20260630135616-20260701135531.pdf',
    clause_page: 'Uplift Rules 2026',
    evidence_required: 'Oil/LPG tank photo, recent fuel invoice, gas grid lookup',
    sort_order: 27,
    is_conditional: 1,
    condition_rule: 'OFF_GAS_UPLIFT_ONLY'
  },

  // STAGE 06: BUS
  {
    stage_code: '06_bus',
    stage_name: '06 BUS',
    section_name: 'Voucher application',
    requirement_key: 'req_bus_voucher_app',
    title: 'BUS Voucher Application Submission',
    short_description: 'Voucher application submitted by installer to Ofgem portal before installation starts.',
    what_is_this: 'Ofgem BUS voucher portal application.',
    why_required: 'Grant voucher must be properly made and approved by Ofgem prior to installation.',
    who_completes: 'BUS Account Administrator',
    who_submits: 'Installer to Ofgem BUS Portal',
    customer_signature_type: 'Installer/portal authentication',
    classification: 'OFFICIAL',
    authority: 'BUS Regulations 2022 / Ofgem V5.1',
    source_url: 'https://www.ofgem.gov.uk/sites/default/files/2026-07/boiler_upgrade_scheme_guidance_for_installers_v5.1_20260630135616-20260701135531.pdf',
    clause_page: 'V5.1 §5',
    evidence_required: 'Ofgem application reference number and submitted portal summary',
    sort_order: 28
  },
  {
    stage_code: '06_bus',
    stage_name: '06 BUS',
    section_name: 'Voucher reference',
    requirement_key: 'req_bus_voucher_reference',
    title: 'Issued BUS Voucher Reference & Validity',
    short_description: 'Issued Ofgem voucher reference number and expiry date (3 months for AWHP, 6 months for GSHP).',
    what_is_this: 'Official BUS Voucher Certificate issued by Ofgem.',
    why_required: 'Installation and commissioning must occur within active voucher validity dates.',
    who_completes: 'Ofgem / BUS Administrator',
    who_submits: 'Internal',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'Ofgem BUS Guidance V5.1 §§1.05–1.06',
    source_url: 'https://www.ofgem.gov.uk/sites/default/files/2026-07/boiler_upgrade_scheme_guidance_for_installers_v5.1_20260630135616-20260701135531.pdf',
    clause_page: 'V5.1 §§1.05-1.06',
    evidence_required: 'Issued Ofgem Voucher document PDF',
    sort_order: 29
  },

  // STAGE 07: MCS
  {
    stage_code: '07_mcs',
    stage_name: '07 MCS',
    section_name: 'Installer certification',
    requirement_key: 'req_mcs_installer_cert',
    title: 'MCS Installer Certification Verification',
    short_description: 'Verification that installer holds active MCS certification for heat pump technology.',
    what_is_this: 'MCS company certificate.',
    why_required: 'Mandatory scheme rule; BUS grants are only payable for MCS-certified installations.',
    who_completes: 'Compliance Officer',
    who_submits: 'MCS / Ofgem',
    customer_signature_type: 'Installer/portal authentication',
    classification: 'OFFICIAL',
    authority: 'MCS Scheme Rules',
    source_url: 'https://mcscertified.com',
    clause_page: 'MCS Installer Certification',
    evidence_required: 'MCS contractor certificate & registration number',
    sort_order: 30
  },
  {
    stage_code: '07_mcs',
    stage_name: '07 MCS',
    section_name: 'MID registration',
    requirement_key: 'req_mcs_mid_registration',
    title: 'MCS MID Installation Registration',
    short_description: 'Registration of completed installation on MCS Installation Database (MID) within 10 working days of commissioning.',
    what_is_this: 'MID database registration entry.',
    why_required: 'Mandatory MCS requirement; must be submitted within 10 working days after commissioning.',
    who_completes: 'MCS Administrator',
    who_submits: 'Installer to MCS MID Portal',
    customer_signature_type: 'Installer/portal authentication',
    classification: 'OFFICIAL',
    authority: 'MCS MID Registration Guidance',
    source_url: 'https://mcscertified.com/registering-your-mcs-installation-on-the-mid/',
    clause_page: '10 Working Day Rule',
    evidence_required: 'MID portal registration receipt and timestamp',
    sort_order: 31
  },
  {
    stage_code: '07_mcs',
    stage_name: '07 MCS',
    section_name: 'MCS certificate',
    requirement_key: 'req_mcs_certificate',
    title: 'Official MCS Installation Certificate',
    short_description: 'Issued official MCS Certificate PDF from the MID portal.',
    what_is_this: 'Official MCS Certificate.',
    why_required: 'Mandatory deliverable for customer handover pack and BUS voucher redemption.',
    who_completes: 'MCS MID System',
    who_submits: 'Installer to Customer & Ofgem',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'MCS Certified',
    source_url: 'https://mcscertified.com',
    clause_page: 'Certificate Delivery Protocol',
    evidence_required: 'Official MCS Certificate PDF',
    sort_order: 32
  },

  // STAGE 08: INSTALLATION
  {
    stage_code: '08_installation',
    stage_name: '08 Installation',
    section_name: 'Installation record',
    requirement_key: 'req_installation_record',
    title: 'Installation Record & Operative Log',
    short_description: 'Record of installation dates, operatives, pipework, insulation, and system decommissioning.',
    what_is_this: 'Installation completion record sheet.',
    why_required: 'Quality assurance and installer accountability file.',
    who_completes: 'Lead Installation Engineer',
    who_submits: 'Internal Quality File',
    customer_signature_type: 'Installer/portal authentication',
    classification: 'PRIME ENERGY INTERNAL',
    authority: 'Prime Energy QMS',
    source_url: 'Internal Standard',
    clause_page: 'Installation Protocol §8',
    evidence_required: 'Completed installation log sheet',
    sort_order: 33
  },
  {
    stage_code: '08_installation',
    stage_name: '08 Installation',
    section_name: 'Serial numbers',
    requirement_key: 'req_installed_serials',
    title: 'Installed Product Serial Numbers & Rating Plates',
    short_description: 'Serial numbers and rating plate photos of heat pump outdoor unit, indoor unit, and cylinder.',
    what_is_this: 'Serial number photographic log.',
    why_required: 'Verified equipment evidence required for MCS certificate and Ofgem redemption audit.',
    who_completes: 'Installer',
    who_submits: 'Internal / Ofgem Audit',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'Ofgem / MCS Audit Rules',
    source_url: 'https://www.ofgem.gov.uk',
    clause_page: 'Audit Evidence §8.2',
    evidence_required: 'Photos of rating plates and serial numbers for all installed units',
    sort_order: 34
  },

  // STAGE 09: COMMISSIONING
  {
    stage_code: '09_commissioning',
    stage_name: '09 Commissioning',
    section_name: 'Commissioning checklist',
    requirement_key: 'req_commissioning_checklist',
    title: 'Heat Pump Commissioning Checklist',
    short_description: 'Commissioning record verifying flow/return temps, flow rate, pressure, safety devices, and controls.',
    what_is_this: 'Completed commissioning certificate.',
    why_required: 'Proves system is fully operational, balanced, and configured to manufacturer instructions.',
    who_completes: 'Commissioning Engineer',
    who_submits: 'Installer to Handover Pack',
    customer_signature_type: 'Installer/portal authentication',
    classification: 'OFFICIAL',
    authority: 'MCS Heat Pump Installation Standard',
    source_url: 'https://mcscertified.com/?standard=the-heat-pump-installation-standard',
    clause_page: 'Commissioning Protocol',
    evidence_required: 'Signed commissioning checklist PDF',
    sort_order: 35
  },
  {
    stage_code: '09_commissioning',
    stage_name: '09 Commissioning',
    section_name: 'Customer demonstration',
    requirement_key: 'req_customer_demonstration',
    title: 'Customer Operational Demonstration',
    short_description: 'Explanation and demonstration of heat pump controls, thermostat, and emergency shutdown to customer.',
    what_is_this: 'Customer handover training confirmation.',
    why_required: 'Ensures customer understands heat pump operation and weather compensation principles.',
    who_completes: 'Commissioning Engineer',
    who_submits: 'Handover Pack',
    customer_signature_type: 'Customer signature',
    classification: 'PRIME ENERGY INTERNAL',
    authority: 'MCS Handover Guidelines',
    source_url: 'https://mcscertified.com',
    clause_page: 'Customer Training §9',
    evidence_required: 'Customer demonstration acknowledgement sheet',
    sort_order: 36
  },

  // STAGE 10: HANDOVER
  {
    stage_code: '10_handover',
    stage_name: '10 Handover',
    section_name: 'Handover',
    requirement_key: 'req_handover_pack',
    title: 'Complete MCS Handover Pack & Customer Receipt',
    short_description: 'Full handover pack delivered to customer containing MCS cert, paid invoice, warranty, heat loss calc, and manuals.',
    what_is_this: 'Official MCS Handover Dossier.',
    why_required: 'Mandatory MCS deliverable specified in MCS Heat Pump Installer Handover Checklist.',
    who_completes: 'Project Manager / Customer',
    who_submits: 'Customer',
    customer_signature_type: 'Customer signature',
    classification: 'OFFICIAL',
    authority: 'MCS Heat Pump Installer Handover Checklist',
    source_url: 'https://mcscertified.com/wp-content/uploads/2019/08/MCS-Installation-Handover-Checklist-Heat-Pump.pdf',
    clause_page: 'Handover Checklist Standard',
    evidence_required: 'Signed customer handover pack receipt & digital pack PDF',
    sort_order: 37
  },
  {
    stage_code: '10_handover',
    stage_name: '10 Handover',
    section_name: 'Paid invoice',
    requirement_key: 'req_paid_final_invoice',
    title: 'Paid Final Invoice with Grant Discount',
    short_description: 'Final invoice displaying gross price, deducted £7,500/£9,000 BUS grant, and paid net balance.',
    what_is_this: 'Paid final customer invoice.',
    why_required: 'Mandatory BUS evidence proving full grant discount was passed to customer upfront.',
    who_completes: 'Finance / Accounts',
    who_submits: 'Installer to Ofgem',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'Ofgem BUS Installer Guidance V5.1',
    source_url: 'https://www.ofgem.gov.uk/sites/default/files/2026-07/boiler_upgrade_scheme_guidance_for_installers_v5.1_20260630135616-20260701135531.pdf',
    clause_page: 'V5.1 §6.4',
    evidence_required: 'Final invoice showing zero balance / proof of customer payment',
    sort_order: 38
  },

  // STAGE 11: REDEMPTION
  {
    stage_code: '11_redemption',
    stage_name: '11 Redemption',
    section_name: 'BUS redemption',
    requirement_key: 'req_bus_redemption_app',
    title: 'BUS Voucher Redemption Application',
    short_description: 'Post-commissioning redemption request submitted to Ofgem portal to claim grant payment.',
    what_is_this: 'Ofgem BUS voucher redemption submission.',
    why_required: 'Triggers Ofgem grant payment to installer account after successful installation.',
    who_completes: 'BUS Account Administrator',
    who_submits: 'Installer to Ofgem BUS Portal',
    customer_signature_type: 'Installer/portal authentication',
    classification: 'OFFICIAL',
    authority: 'Ofgem BUS Installer Guidance V5.1',
    source_url: 'https://www.ofgem.gov.uk/sites/default/files/2026-07/boiler_upgrade_scheme_guidance_for_installers_v5.1_20260630135616-20260701135531.pdf',
    clause_page: 'V5.1 §6',
    evidence_required: 'Ofgem redemption portal submission receipt',
    sort_order: 39
  },
  {
    stage_code: '11_redemption',
    stage_name: '11 Redemption',
    section_name: 'Payment reference',
    requirement_key: 'req_grant_payment_rec',
    title: 'Grant Payment Reconciliation & Reference',
    short_description: 'Ofgem payment reference number, remittance advice, and bank reconciliation.',
    what_is_this: 'Grant payment receipt and reconciliation document.',
    why_required: 'Financial closure of BUS voucher redemption.',
    who_completes: 'Finance',
    who_submits: 'Internal Accounts',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'Ofgem Payment Record',
    source_url: 'https://www.ofgem.gov.uk',
    clause_page: 'Payment Protocol §11',
    evidence_required: 'Ofgem remittance advice note and bank transaction record',
    sort_order: 40
  },

  // STAGE 12: AUDIT FILE
  {
    stage_code: '12_audit_file',
    stage_name: '12 Audit File',
    section_name: 'Full evidence list',
    requirement_key: 'req_master_audit_file',
    title: 'Master Job Audit Dossier',
    short_description: 'Consolidated audit dossier containing all eligibility, survey, design, installation, commissioning, and grant evidence.',
    what_is_this: 'Master compliance audit archive.',
    why_required: 'Provides complete audit defensibility for Ofgem or MCS compliance inspections.',
    who_completes: 'Compliance Officer',
    who_submits: 'Internal Audit File',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'BUS Regulation 17(1)(a) / Ofgem Audit Protocol',
    source_url: 'https://www.ofgem.gov.uk',
    clause_page: 'Audit Guidance V5.1',
    evidence_required: 'Complete indexed project archive zip / directory',
    sort_order: 41
  },
  {
    stage_code: '12_audit_file',
    stage_name: '12 Audit File',
    section_name: 'Retention date',
    requirement_key: 'req_statutory_retention',
    title: 'Statutory 6-Year Information Retention Lock',
    short_description: 'System-managed retention lock ensuring all project records are retained for at least 6 years from application date.',
    what_is_this: 'Statutory compliance retention lock.',
    why_required: 'Mandatory obligation under BUS Regulation 17(1)(a).',
    who_completes: 'System / Compliance Officer',
    who_submits: 'Internal Archive',
    customer_signature_type: 'No signature',
    classification: 'OFFICIAL',
    authority: 'BUS Regulation 17(1)(a)',
    source_url: 'https://www.legislation.gov.uk/uksi/2022/565/body',
    clause_page: 'Regulation 17(1)(a)',
    evidence_required: '6-year retention schedule lock confirmation',
    sort_order: 42
  }
];

export async function seedSubmissionForJob(submissionId: string, leadData: any) {
  // Populate default 42 requirements for a newly created submission workspace
  const now = new Date().toISOString();
  
  // Determine conditionals based on job inputs
  const isGshp = (leadData.technology || '').toLowerCase().includes('ground');
  const isSelfBuild = (leadData.property_status || '').toLowerCase().includes('self-build');
  const isOffGasUplift = (leadData.grant_category || '').includes('£9,000') || ((leadData.on_off_gas_grid || '').toLowerCase().includes('off') && ['Heating Oil', 'Bulk LPG'].includes(leadData.existing_fuel || ''));
  const isCylinderApplicable = leadData.cylinder_applicable !== 0;

  for (const tpl of MASTER_REQUIREMENTS_TEMPLATE) {
    let initialStatus = 'Pending';
    let isCond = tpl.is_conditional || 0;

    // Apply conditional rules automatically
    if (tpl.condition_rule === 'GSHP_ONLY' && !isGshp) {
      initialStatus = 'Not Required';
    } else if (tpl.condition_rule === 'SELF_BUILD_ONLY' && !isSelfBuild) {
      initialStatus = 'Not Required';
    } else if (tpl.condition_rule === 'OFF_GAS_UPLIFT_ONLY' && !isOffGasUplift) {
      initialStatus = 'Not Required';
    } else if (tpl.condition_rule === 'CYLINDER_ONLY' && !isCylinderApplicable) {
      initialStatus = 'Not Required';
    }

    const itemId = `sub_item_${Math.random().toString(36).substring(2, 11)}_${Date.now()}`;
    await db.execute(
      `INSERT INTO submission_items (
        id, submission_id, stage_code, stage_name, section_name, requirement_key,
        title, short_description, what_is_this, why_required, who_completes, who_submits,
        customer_signature_type, classification, status, is_conditional, condition_rule,
        evidence_required, authority, source_url, clause_page, sort_order, created_at, updated_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        itemId, submissionId, tpl.stage_code, tpl.stage_name, tpl.section_name, tpl.requirement_key,
        tpl.title, tpl.short_description, tpl.what_is_this, tpl.why_required, tpl.who_completes, tpl.who_submits,
        tpl.customer_signature_type, tpl.classification, initialStatus, isCond, tpl.condition_rule || null,
        tpl.evidence_required, tpl.authority, tpl.source_url, tpl.clause_page, tpl.sort_order, now, now
      ]
    );
  }
}
